### ISSUE TITLE
After a value is selected the Typeahead doesn't work a second time

### ISSUE THREAD

**Issue by ironbull45** [Blazored/Typeahead#100]
I have put the component on my layout page:

`<component type="typeof(razorComponents.AutoComplete)"  render-mode="ServerPrerendered" />`

When a value is selected it works fine. The value is captured & one is redirected to a new page:

`_navigationManager.NavigateTo($"account/{accountId}",true);`

Once on the new Account page, you can type in the Autocomplete component again, but no event fires. This is probably a Blazor issue more than a problem with this control. I would appreciate it if you could help me either way :)

**Comment by chrissainty** [comment]
Hi @ironbull45, I'd be happy to help, could you provide me with a repro of the issue? The two lines above aren't much to go on :)

**Comment by ironbull45** [comment]
Thanks Chris.

I found the issue, but I still don't know how to fix it.

I select the value from the Typeahead & navigate to a new page using a force refresh. The page loads, but the Typeahead doesn't work:

```
	public void RedirectToAccount(string accountId)
	{
		_navigationManager.NavigateTo($"account/{accountId}");
	}
```

If I don't force the refresh

`_navigationManager.NavigateTo($"account/{accountId}");`

the Typeahead still works, but the account page doesn't load.

**Comment by chrissainty** [comment]
Again, could you provide some more code as it’s really hard to diagnose
this type of issue without a working example. There is nothing obvious from
what’s you’ve mentioned.

**Comment by ironbull45** [comment]
Sorry.

```
@using Blazored.Typeahead;
@using XYZ.Provisioning.API.Models.DTO;
@using System.Web;
@inject XYZ.Provisioning.API.IAccountClient _accountClient
@inject NavigationManager _navigationManager


<div class="row">
	<div class="col-md-2" style="margin-top:10px;font-weight:bold">
		Employee
	</div>
	<div class="col-md-5" style="margin-right: -130px;">
		<BlazoredTypeahead SearchMethod="SearchAccounts"
						   @bind-Value="SelectedAccount" MaximumSuggestions="50" MinimumLength="2">
			<SelectedTemplate>
				@context.LastName
			</SelectedTemplate>
			<ResultTemplate>
				<span style="font-weight: bold">@context.LastName, @context.FirstName @context.MiddleInitial</span>
				<br/>@context.LocationDescription
				<br/>@context.TitleDescription
			</ResultTemplate>
		</BlazoredTypeahead>
	</div>
</div>

@if (SelectedAccount != null)
{
	RedirectToAccount(SelectedAccount.AccountId.ToString());

}

@code {


	private AccountSummaryDTO SelectedAccount;

	private async Task<IEnumerable<AccountSummaryDTO>> SearchAccounts(string searchText)
	{
		var foundAccounts = await _accountClient.SummariesAsync(searchText, null, null);
		var accountList = new List<AccountSummaryDTO>();
		foreach(API.AccountSummaryDTO foundAccount in foundAccounts.Result.Results)
		{
			AccountSummaryDTO account = new AccountSummaryDTO();
			account.AccountId = foundAccount.AccountId;
			account.LoginName = foundAccount.LoginName;
			account.LastName = foundAccount.LastName;
			account.FirstName = foundAccount.FirstName;
			account.MiddleInitial = foundAccount.MiddleInitial;
			account.LocationDescription = foundAccount.LocationDescription;
			account.TitleDescription = foundAccount.TitleDescription;

			accountList.Add(account);
		}
		return accountList;
	}

	public void RedirectToAccount(string accountId)
	{
		_navigationManager.NavigateTo($"../account/{accountId}",true);
		

	}

}
```

I do notice when I do the force refresh I'm losing the styling on the Typeahead but I looked in Chrome & the reference to 	<link href="_content/Blazored.Typeahead/blazored-typeahead.css" rel="stylesheet" /> is still there.

If this helps further, this is a Razor pages application, but I wanted to use your Blazor component.

**Comment by ironbull45** [comment]
This is the layout page where the Typeahead is being called:

```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - XYZ.Provisioning.Web.Razor</title>

	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	@*<link rel="stylesheet" href="~/css/bootstrap-flatly.css" asp-append-version="true" />*@
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	@* Kendo CSS after defaults *@
	<link rel="stylesheet" href="~/lib/telerik/styles/kendo.common-bootstrap.min.css" />
	<link rel="stylesheet" href="~/lib/telerik/styles/kendo.bootstrap.min.css" />

	<link rel="stylesheet" href="https://unpkg.com/@@progress/kendo-theme-default@@latest/dist/all.css" />

	<link href="_content/Blazored.Typeahead/blazored-typeahead.css" rel="stylesheet" />


	<script src="~/lib/jquery/dist/jquery.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
	@* Kendo scripts after defaults *@
	<script src="~/lib/telerik/js/kendo.all.min.js"></script>
	<script src="~/lib/telerik/js/kendo.aspnetmvc.min.js"></script>
	
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div style="padding-right:20px">
					<a class="navbar-brand" asp-controller="Home" asp-action="Index">
						<img src="~/images/XYZLogo.gif" class="d-inline-block align-top" alt="Logo">
						Provisioning
					</a>
				</div>
				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					<p class="nav navbar-text navbar-right" style="padding-left: 20px">Hello, @User.Identity.Name!</p>
					<div style="width:600px">
						<component type="typeof(razorComponents.AutoComplete)"  render-mode="ServerPrerendered" />
					</div>
					@*<div style="border:solid thin">
							<vc:employee-auto-complete default-model="new Components.EmployeeAutoComplete.DefaultModel()"></vc:employee-auto-complete>
						</div>*@
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
						</li>
					</ul>

				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2019 - XYZ.Provisioning.Web.Razor - <a asp-area="" asp-page="/Privacy">Privacy</a>
		</div>
	</footer>

	<script src="_content/Blazored.Typeahead/blazored-typeahead.js"></script>
	<script src="_framework/blazor.server.js"></script>

	@RenderSection("Scripts", required: false)
</body>
</html>
```

**Comment by chrissainty** [comment]
Do you have any errors appearing in the browser console? Also, have you got detailed errors turned on in your startup class?

```csharp
services.AddServerSideBlazor(o => o.DetailedErrors = true);
```

**Comment by ironbull45** [comment]
I will check, but I've narrowed down the problem further. If I redirect with a force refresh to a page that doesn't have any parameters:

`_navigationManager.NavigateTo($"test",true);`

the Typeahead still works. If I change the Page to accept routing parameters, the Typeahead stops working:

`@page "{accountId?}"`

**Comment by ironbull45** [comment]
Bingo. Once I add a routing parameter, I see the following reference errors:

![libraries_not_found](https://user-images.githubusercontent.com/1727015/71415709-09e9fc00-262b-11ea-95bb-a8e26661ce71.PNG)

**Comment by vertonghenb** [comment]
Looks to me that you didn't include the .js and .css files in the _host.cshtml page. 
Check the readme in this repo to see how to add them.

**Comment by ironbull45** [comment]
haha. no. This is a Razor application. I'm trying to use this blazor component in my app. I added the references to _layout.cshtml. Remember, it works fine initially. The Typeahead also works if I'm redirecting to a page without a routing parameter. It just doesn't work when I'm redirecting to a page with a routing parameter.

**Comment by ironbull45** [comment]
So I put the _framework & _content links into local sources as follows:

```
	@*<script src="_content/Blazored.Typeahead/blazored-typeahead.js"></script>*@
	<script src="~/lib/blazor_typeahead/js/blazor_typeahead.js"></script>
	@*<script src="_framework/blazor.server.js"></script>*@
	<script src="~/lib/blazor/blazor_server.js"></script>
```

And now I get the following errors:
![more_blazor_messages](https://user-images.githubusercontent.com/1727015/71418751-28a3bf00-263a-11ea-8ba5-918865e299c3.PNG)

Looks like more references issues, I don't know how to fix at this point.

**Comment by chrissainty** [comment]
@ironbull45 I've just had a thought, could you update your code to add a `/` to the following elements.

```
<link href="/_content/Blazored.Typeahead/blazored-typeahead.css" rel="stylesheet" />

<script src="/_content/Blazored.Typeahead/blazored-typeahead.js"></script>
<script src="/_framework/blazor.server.js"></script>
```

**Comment by ironbull45** [comment]
I moved your suggestions into the layout page & have the same result. What really gets me, though, is how this works fine as long as there are no routing parameters. With the routing parameter, I still get:

![libraries_not_found_2](https://user-images.githubusercontent.com/1727015/71547738-07acd800-2972-11ea-9d07-ce0b827faf63.PNG)

**Comment by chrissainty** [comment]
![image](https://user-images.githubusercontent.com/6171719/71547792-8dde1400-299c-11ea-9af7-f5d16b457f40.png)

I think the issue is in the highlighted sections, notice the path, `/test/_blazor/...` I don't think the `test` should be there. Have you got a base tag in your layout page?

**Comment by ironbull45** [comment]
Dude, I could kiss you. I'm new to .NET Core Razor. What is the base tag doing?

How can I show my gratitude for the time you spent resolving this?

**Comment by chrissainty** [comment]
Your thanks to more than enough, I'm just glad we got to the bottom of it 😄!
