### ISSUE TITLE
Example code suggestion

### ISSUE THREAD

**Issue by jspinella** [Blazored/Typeahead#101]
In the usage example in Readme.md, ToLower() is being used when comparing Films with the searchQuery:

`return await Task.FromResult(Films.Where(x => x.Title.ToLower().Contains(searchText.ToLower())).ToList());`

Why not instead use:

`return await Task.FromResult(Films.Where(x => x.Contains(searchText, StringComparison.OrdinalIgnoreCase)).ToList());`

**Comment by chrissainty** [comment]
Hi James,

That code is just a simple example and not a lot of thought went into it. The focus of that code is to show how to use the component, nothing more.

**Comment by jspinella** [comment]
All good man, thanks for creating an awesome typeahead!
