### ISSUE TITLE
Typeahead result mixing with text on the page

### ISSUE THREAD

**Issue by ironbull45** [Blazored/Typeahead#105]
I'm using Blazored Typeahead in the MainLayout.razor so it appears globally at the top of the page.

Whenever I have a long result the text from the result collides with the text on my page. I've tried lowering the Z-index on the page components. Sometimes this has worked, sometimes it doesn't. When the collision occurs, it presents a jumbled looking result & also prevents selection.

Is there a global way of handling this?

**Comment by chrissainty** [comment]
Could you provide a screenshot of what this looks like? I'm having trouble visualising it :)

**Comment by ironbull45** [comment]
unfortunately, the data is sensitive. Let me see if I can come up with test data.

**Comment by ironbull45** [comment]
I thought of a way to obscure the data.

So here is the first photo that show the page without values:

![screen_without_values](https://user-images.githubusercontent.com/1727015/72076111-09a45e80-32c3-11ea-9591-96ed452c05a2.png)

Then, the results from a Typeahead which shows the results jumbled with the labels on the page:

![autocomplete_overlapping_text](https://user-images.githubusercontent.com/1727015/72076171-20e34c00-32c3-11ea-85af-d23913b4a0f2.png)

**Comment by chrissainty** [comment]
Thanks for the screenshots, made things much easier.

Do you have any special styling on your labels? Have you tried adjusting their z-index, just to see what happens?

**Comment by ironbull45** [comment]
I drove myself crazy with z-index on different divs. I found this on the Telerik site even though I'm not using a Telerik control for this issue:

https://docs.telerik.com/blazor-ui/troubleshooting/general-issues

I ended up putting my div in a bootstrap Card & set the z-index to a negative number & that worked. I'll isolate the issue when I have more time. Thanks!
