### ISSUE TITLE
Do you have manual Install instructions?

### ISSUE THREAD

**Issue by kirk-mcneil** [Blazored/Typeahead#109]
Hi,
This looks like a great addition to Blazor and I'd like to try it in our projects but can't get it to install on our core 3.1 MVC project. I'm using Blazor components and have them working in other areas but the TypeAhead install is failing (I'm guessing) because this is a hybrid project. 

Would you please supply some manual instructions?
Thanks!
Kirk

**Comment by chrissainty** [comment]
Could you provide some information about what isn't working? Errors, etc... I believe others are using the typeahead in hybrid solutions so we should be able to get things going for you.

**Comment by kirk-mcneil** [comment]
Hi Chris, Thanks for your quick response! My initial assessment was written while I was frustrated about my ignorance since Blazor is so new to me. 

I had installed the nuget and tried to implement a custom component. There were no errors on the install. The input was put on the screen but nothing happened when I typed. I put a breakpoint in the code and it wasn't getting called. I looked through the generated code and it didn't look like there was anything but an input. 

I downloaded the Blazored sample project and that worked great. I compared it to my project and started trying to get them to have the same files in the same locations - this is where my ignorance kicked in. I didn't realize where the Blazored package was and created a rabbit hole of errors that didn't make sense. I thought the install had failed and I wrote that to you.

I removed all the files I took from the sample project and now see that it isn't the install that's failing. I'm not sure what I'm doing wrong but I would appreciate any help you can offer. 

Here's where I'm at: I installed the nuget, put in the css, js and _import references, created a custom component that has the Blazored Remote Data Example tags and put in custom code to my database. When I put a breakpoint in my custom code it is never called.

What can I do to help you troubleshoot?
Thanks!
Kirk

**Comment by vertonghenb** [comment]
It could be that your searchmethod is never called. To investigate the issue, please provide us with a small repo which reproduces this behavior. Currently it's impossible to troubleshoot.

Thanks!

**Comment by chrissainty** [comment]
I would second what @vertonghenb has suggested. The only other thing I can think of is have you included the JavaScript files for Blazor in your application? Not just the ones for this Typeahead.

**Comment by kirk-mcneil** [comment]
Good morning and thanks again for your quick responses. 
@vertonghenb I created a new solution with bare bones and was able to reproduce what I'm seeing in my project. Where do I send/upload it to?

@chrissainty Yes, I did put the Blazor js file in the _Layout. I followed, as best I could, the instructions I found on this page: https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1

**Comment by kirk-mcneil** [comment]
I signed up for a hosting service. Here's a link to the solution:

https://mega.nz/#!FBdTma4b!cPYwaXZBTCtX7A2f7jjWY_lZrKPdwu-PEF9WcQHytlg

**Comment by kirk-mcneil** [comment]
Were you able to open the solution and see the problem I'm facing?

**Comment by vertonghenb** [comment]
@kirk-mcneil Not to be annoying or anything but I'd rather not download/open a mega file. Please provide a public repository hosted on GitHub with a reproduction of the issue you're facing.

**Comment by kirk-mcneil** [comment]
I didn't know I could do that. Can you see this?
https://github.com/kirk-mcneil/testFiles

**Comment by vertonghenb** [comment]
@kirk-mcneil 
Found the issue but it has nothing to do with the typeahead component. 
Please check your _Layout.cshtml in the Views\Shared folder.
Adjust the following:
-  **Move** Line 13 : `<script src="_framework/blazor.server.js"></script>` to the end of the html  `</body>` element.

It's best practise to always add .js or script files at the end of the `<body>` element or use the `defer` or `async` keywords when you don't. More information can be found [here](https://stackoverflow.com/questions/436411/where-should-i-put-script-tags-in-html-markup)


Giffy provided (click to enlarge)
![img](https://i.imgur.com/vBfL7Dv.gif)

**Comment by kirk-mcneil** [comment]
Fantastic! Thanks @vertonghenb Sorry to take up your time on something so simple.
