### ISSUE TITLE
Giving the component a name/id

### ISSUE THREAD

**Issue by kirk-mcneil** [Blazored/Typeahead#113]
Hi Chris and Blazored team,
I'm using the Typeahead component in a dynamic form, created from database entries. Would you please help me understand how I can get the name/id field from the database to the model through the component?

In the below code you can see I'm constructing an input for the default and using the @param from the foreach to identify the control that sent the data. What's the best way to get param through the component?

            @foreach (var crit in GetCriteria().OrderBy(a => a.Display_Order))
            {
                var param = @crit.Parameter_Name;
            <div class="form-group row">

                <label for="@crit.Parameter_Name">@crit.Display_Name</label>
                @switch (crit.Item_Type)
                {
                    case "EmployeeSearch":
                        if (@crit.Display_Name == "Marketing")
                        {
                            <BlazoredTypeahead SearchMethod="GetMarketingRep"
                                               @bind-Value="_report.SelectedMarketingRep"
                                               Debounce="500"
                                               Context="rep"
                                               placeholder="Search by marketing rep name...">
                                <ResultTemplate>
                                    @rep.FirstPart<b>@rep.MiddlePart</b>@rep.SecondPart
                                </ResultTemplate>
                                <SelectedTemplate>
                                    @rep.Entity_Name
                                </SelectedTemplate>
                                <NotFoundTemplate>
                                    No Marketing Rep found containing that text
                                </NotFoundTemplate>
                            </BlazoredTypeahead>
                        }
                    default:
                        <input id="@param" name="@param" class="form-control" @onchange="@(e => OnDataChanged(e, param))" />
                        break;
                }
            </div>
            }

Thanks!
Kirk

**Comment by chrissainty** [comment]
Hi Kirk, apologies for the delay, I missed your issue being raised. 

I've looked at your code but I'm not sure what you're trying to do and where the problem with the control is. Could you give bit more detail?

**Comment by kirk-mcneil** [comment]
Hi Chris,
I'm all set :)
I was able to accomplish my task by putting in a hidden input and binding the value to the selected object with the param name. 
Thanks for getting back to me.
Kirk
