### ISSUE TITLE
BlazoredTypeahead.Values requires a IList<T>

### ISSUE THREAD

**Issue by sven-n** [Blazored/Typeahead#114]
For my use case, it would be great to just require a ```ICollection<T>```. In my business models and EF Core classes, I just use ```IList<T>```, when a explicit order is required. Other than that (most cases) I use ```ICollection<T>```.

I found no reason why it shouldn't work just with ```ICollection<T>```. Do you see any reason which would prevent a change? If not, I'd like to create a pull request :)

**Comment by sven-n** [comment]
I have to admit, it's not as easy as replacing ```IList<T>``` with ```ICollection<T>```. Ofc, the component would work, but the consuming code might not compile after the change, because of a changed ```ValuesChanged``` return type - it would be a breaking change.

**Comment by chrissainty** [comment]
Hi @sven-n, sorry for the long reply I've been busy with some talks. 

Thanks for the suggestion but due to the breaking change I don't think it's something I'd want to do. The change just doesn't have enough value, in my opinion, to warrant the disruption it would cause.
