### ISSUE TITLE
BlazoredTypeaheadInputBase<> could not be found

### ISSUE THREAD

**Issue by fnils** [Blazored/Typeahead#12]
I just upgraded to version 3.0.1 and now I get this error.
I am using the standalone version. Did I miss something after the upgrade?

The type or namespace name 'BlazoredTypeaheadInputBase<>' could not be found (are you missing a using directive or an assembly reference?)	D:\dev\test\obj\Debug\netcoreapp3.0\RazorDeclaration\Forms\BlazoredTypeaheadInput.razor.g.cs	56

**Comment by fnils** [comment]
Sorry, I am apparently blind. I missed to add "Context" on Context="Person".

**Comment by fnils** [comment]
If I add @using Blazored.Typeahead.Forms in _imports.razor the first error disappears but I get the error below instead. I haven't added the EditForm code here. If I do I still get this error.

InvalidOperationException: Object of type 'Blazored.Typeahead.BlazoredTypeahead`1[[Test.Shared.Area, Test.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' does not have a property matching the name 'bind-Value'.

**Comment by chrissainty** [comment]
Have you updated your code to use `bind-Value` instead of `bind-Item`?

**Comment by fnils** [comment]
Yes, I have changed it. The code looks like this:
        <BlazoredTypeahead SearchMethod="@SearchAreas"
                           bind-Value="@SelectedArea"
                           Placeholder="Search">

            <SelectedTemplate Context="Area">
                @Area.Name
            </SelectedTemplate>
            <ResultTemplate Context="Area">
                @Area.Name (@Area.Descr)
            </ResultTemplate>
            @*<NotFoundTemplate>
                    @if (notFound)
                    {
                    @:Sorry, there weren't any search results.
                    }
                </NotFoundTemplate>*@
        </BlazoredTypeahead>

**Comment by fnils** [comment]
I upgraded to version 3.0.2 and now the first error seems to be gone.
But I get (which is the same as before I guess):
InvalidOperationException: Object of type 'Blazored.Typeahead.BlazoredTypeahead`1[[Test.Shared.Area, Test.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' does not have a property matching the name 'bind-Value'.

**Comment by fnils** [comment]
I don't know if it makes a difference but at the same time as I upgraded to version 3.01 I also upgraded to asp.net core 3.0-preview-6.

**Comment by chrissainty** [comment]
Sorry for the long reply @fnils. I'm now doing the upgrade to Preview 6, it should be on NuGet in the next hour. Give it a go and let me know if it sorts the issue.

**Comment by fnils** [comment]
Thank you! I'll check it out during the day hopefully. Otherwise tomorrow.

**Comment by fnils** [comment]
It's working! Thank you!

**Comment by chrissainty** [comment]
No problem :)
