### ISSUE TITLE
Can we use a delegate for SearchMethod?

### ISSUE THREAD

**Issue by dolare1** [Blazored/Typeahead#121]
Hello, we are trying to develop a reusable typeahead control that can be extended. I was wondering if it is possible to use a delegate instead of an actual method for SearchMethod attribute?

Any pointers?

**Comment by chrissainty** [comment]
Hi @dolare1, is this related to this control? What about the current search method approach doesn't work for you?

**Comment by dolare1** [comment]
We are using blazored typeahead control. We use it in various locations in our project to retrieve projects, employees, resources etc. Instead of writing the razor code in every location we thought it would be helpful if we could implement a reusable component and then just pass the necessary attributes as "parameters". 

this is where it would be helpful to pass a delegate to "SearchMethod" attribute. For example, we will have three different methods for projects, employees and resources. So, was thinking that client would just pass the delegate and the reusable control would use that. Is that possible?

**Comment by chrissainty** [comment]
The `SearchMethod` parameter is a func delegate, so you can pass in whatever method you wish as long as it accepts a string and returns an `IEnumerable<T>`. If you want to wrap this component inside another (I think that's what you're doing, apologies if I've misunderstood) then have you component acces a paramter with the same signature and that can be passed in by whatever is using your component.

**Comment by SphtKr** [comment]
@dolare1 I'm trying to do the same thing I think, and I think I figured this part out. Here's my attempt:

```
@using App.Core
@using Blazored.Typeahead

@inject Repository.UnitOfWork Uow;

@inherits Blazored.Typeahead.BlazoredTypeahead<Person, Person>

@code {
    protected override void OnInitialized()
    {
        SearchMethod = SearchPeople; // <-- Here may answer your question

        RenderFragment<Person> defaultTemplate = (person) =>@<div class="person-slug">@person.Name.ToFormalDisplayName()</div>;
        if (SelectedTemplate == null)
        {
            SelectedTemplate = defaultTemplate;
        }
        if (ResultTemplate == null)
        {
            ResultTemplate = defaultTemplate;
        }
        base.OnInitialized();
}

// v-- Here is the method
private async Task<IEnumerable<Person>> SearchPeople(string searchText) 
{
    return await Task.FromResult(Uow.People.Where(Person.Matches(searchText)));
}

}
```

However, I'm not sure that it works because I can't yet figure out how to get the Razor Markup to render for my subclass... curious what you did. Maybe between the two of us we can figure out if this works, or if any addition/change to the base class is needed.

**Comment by chrissainty** [comment]
I'm just doing some housekeeping and looking at this issue there isn't anything which needs to be done on the component, so I'm going to close it. If there is a problem or a feature which needs changes to the control please open a new issue specifically for that change.
