### ISSUE TITLE
[Bug]  element.focus is not a function

### ISSUE THREAD

**Issue by gaffkins** [Blazored/Typeahead#122]
After select result I got many errors
"Microsoft.JSInterop.JSException: element.focus is not a function"
After that component stop working.

Blazor Server side.

`<BlazoredTypeahead TItem="string" TValue="string" Value="SelectedFilm" ValueExpression="@(() => SelectedFilm)"  ValueChanged="@(e => Console.WriteLine(e))" placeholder="Search..." Debounce="1000" SearchMethod="SearchFilms">
    <SelectedTemplate>
        @context
    </SelectedTemplate>
    <ResultTemplate>
        @context
    </ResultTemplate>
    <NotFoundTemplate>
        Sorry, there weren't any search results.
    </NotFoundTemplate>
    <FooterTemplate>
        <button>Show more</button>
    </FooterTemplate>
</BlazoredTypeahead>`

**Comment by vertonghenb** [comment]
@gaffkins Which version are you using? We had an issue with the same problem but that seemed to be fixed. Try to use the latest version and see if the issue still persists.

**Comment by vertonghenb** [comment]
@gaffkins any update on this?

**Comment by omora** [comment]
The same error happends to me

**Comment by needhelp33** [comment]
Did anyone find any solution?

**Comment by arivera12** [comment]
This library was working properly for me, but after making a few changes now this error is being thrown...

**Comment by chrissainty** [comment]
Thanks for the info @arivera12. I’m working on a very big update for Blazored Modal which should be out this week. Once I’m done with that I’m going to be working on the Typeahead.

**Comment by needhelp33** [comment]
@arivera12 after reading your comment I tried to set an initial SelectedValue and that solved the problem for me. Thanks

**Comment by shaneconnolly** [comment]
Hi guys, I'm also having this issue. @needhelp33 could you give me a sample of the code you used for the 'SelectedValue' workaround? I don't see that as a listed parameter. Thanks.
And thanks @chrissainty for this project.

**Comment by needhelp33** [comment]
Hi @shaneconnolly,

This worked out for me:

<BlazoredTypeahead SearchMethod="GetSome"  Value="SelectedGroup"  ValueChanged="GroupChanged"	   TItem="Articles"   TValue="Articles"   ValueExpression="@( () => SelectedGroup)"><SelectedTemplate Context="group"></SelectedTemplate><ResultTemplate Context="group">@group.Designation</ResultTemplate></BlazoredTypeahead>

The important part, set a  'SelectedGroup' when rendering the page: 

protected override async Task OnInitializedAsync()
{
    SelectedGroup = new YourObject(){Id= "1", Designation="sel" };
    await ...
}

**Comment by needhelp33** [comment]
Hi @shaneconnolly,

This worked out for me:

`<BlazoredTypeahead SearchMethod="GetSome"  Value="SelectedGroup"  ValueChanged="GroupChanged" TItem="Articles"			   TValue="Articles"  ValueExpression="@( () => SelectedGroup)">	<SelectedTemplate Context="group"></SelectedTemplate><ResultTemplate Context="group">@group.Designation</ResultTemplate></BlazoredTypeahead>`

The important part, set a 'SelectedGroup' when rendering the page:

protected override async Task OnInitializedAsync()
{
SelectedGroup = new YourObject(){Id= "1", Designation="sel" };
await ...
}

**Comment by shaneconnolly** [comment]
Thanks @needhelp33, I understand what you mean now. 
I've just realised that my issue was actually related to the fact that I was using the ValueChanged event instead of @bind-Value as per #124 and I hadn't followed @osheab87's advise here: https://github.com/Blazored/Typeahead/issues/124#issuecomment-632820208
