### ISSUE TITLE
[Feature] Improve the keyboard experience around deselecting options in multi-select mode

### ISSUE THREAD

**Issue by magahl** [Blazored/Typeahead#125]
https://github.com/Blazored/Typeahead/blob/1ab77d11cd7049efae3576d0fe229ac41ebe294d/src/Blazored.Typeahead/BlazoredTypeahead.razor.cs#L366

As the title says, am I missings something or why is this done? Should it not just skip the add part? Or perhaps replace it at at the very least. 

If there is a good reason for this, just close this issue.

**Comment by chrissainty** [comment]
Hey @magahl, good question and I appreciate it looks odd 🙂. The reason is so if someone is just using a keyboard and they select an item by mistake, they can use the keyboard to remove it by selecting it again.

**Comment by magahl** [comment]
Aight. Then I understand. A better soultion might be to navigate with backspace to delete the latest. and arrow to navigate and select an earlier value. Much like this gif where i only use the keyboard. 

![KeyboardDelete](https://user-images.githubusercontent.com/1409979/77741192-c67da000-7014-11ea-8c4a-8fac40b23113.gif)

I understand that there is alot of work to implement this and i don't expect you to do it :)

**Comment by chrissainty** [comment]
@magahl Yes, I agree that would be a nice improvement on the current functionality. I'd be happy to take a PR to improve it if you're interested? 🙂

**Comment by magahl** [comment]
Yes I am defintly interested. Right now I don't have time though. But i keep it in mind if I run into some extra time in the foreseeable future :)

**Comment by chrissainty** [comment]
Cool, I'll leave this issue open and tag it as a feature.

I would ask though if you realise you can't get to it for the foreseeable future, if you could just drop a comment so we know whats going on. Is that ok?

**Comment by magahl** [comment]
Yes, o fcourse. No problem :)

**Comment by magahl** [comment]
I will not have time to do this in coming month at least @chrissainty

**Comment by chrissainty** [comment]
Ok, thanks for letting me know @magahl
