### ISSUE TITLE
[Question] Unable to pick an item from typeahead using mouse

### ISSUE THREAD

**Issue by ghok-rgb** [Blazored/Typeahead#128]
My apologies in advance if i misclassified the issue type.

I recently upgraded to v4.3.0. Below is our typeahead markup in the razor page:

```
<BlazoredTypeahead SearchMethod="@SearchUsers" @bind-Value="@SelectedUser" EnableDropDown="true" MaximumSuggestions="3000" placeholder="Search User...">
                    <SelectedTemplate>
                        @context.ADName (@context.Email)
                    </SelectedTemplate>
                    <ResultTemplate>
                        @context.ADName (@context.Email)
                    </ResultTemplate>
                </BlazoredTypeahead>
```

For some reason, if we use mouse to scroll through the items in the typeahead control and select an item, SelectedItem's value is not set. I don't see any browser console errors. It's as if it just ignored my mouse click. However, once I open the drop down, if I scroll down using down arrow and select an item using "enter" key, SelectedItem's value is properly set.

Am I missing anything in the markup? Could you please advise?

Thanks.

**Comment by chrissainty** [comment]
Hey @ghok-rgb, can I just clarify. Are you saying when the suggestion list is open, and you click an item with the mouse, it is not selected?

Just for reference, we don't have any functionality to handle the wheel event in the typeahead. So I wouldn't expect you'd be able to scroll through items in the suggestion list with the mouse wheel.

**Comment by ghok-rgb** [comment]
Thanks Chris. I am not using mouse wheel to scroll down the list. My issue is when I open the list and select an item using mouse, the SelectedItem is not set.

Please standby, I will try to reproduce the issue and share the code with you.

**Comment by x6060x** [comment]
+1 I can reproduce the issue with the sample example in Firefox and Chrome. I'm using Blazor WebAssembly btw.

**Comment by chrissainty** [comment]
@x6060x Can you describe exactly what you did?

**Comment by chrissainty** [comment]
@ghok-rgb @x6060x I've been trying to replicate the issue. So far I've tested it on Windows using Edge, Chome and FireFox. I've also done the same on MacOS in all three browsers. Everything is working as expected.

Can you provide any further details?

**Comment by x6060x** [comment]
@chrissainty Today I was playing more with that control. I'm using the provided example in the home Github page. The issue is not replicating every time, but I found that it's caused by racing condition when the onclick event is triggered when an item is selected:
```csharp
@onclick="@(_ => SelectResult(item))"
```
Onblur on the input text field is called too soon sometimes and it's breaking the selection.

You can replicate the issue every time by decreasing the delay value in ResetControl(), which is 200ms at the moment. When I increased the delay to 400ms the issue disappeared completely for me. When I removed the delay the issue started replicating every time. Now I'm looking for more elegant solution so I don't depend on that delay at all.

BTW, nice control!

**Comment by chrissainty** [comment]
Thanks for the feedback @x6060x. I agree the solution isn't great. It's always been something we'd want to get rid of if at all possible. Are you planning on raising a PR with a better solution?

**Comment by ghok-rgb** [comment]
@x6060x could you please explain your workaround? where onblur come into picture?

**Comment by x6060x** [comment]
@chrissainty @ghok-rgb  I tried different possible solutions. I found a StackOverflow [topic](https://stackoverflow.com/questions/17769005/onclick-and-onblur-ordering-issue) explaining that using event.preventDefault() on the onMouseDown event should work, but it didn't work for me for some reason. If it worked it would be a "perfect" solution.
I have 2 working fixes at the moment - one is changing the items selection event from onclick to onmousedown and removing the delay completely. This will work with the provided example, however in my use case I'd like to have a button in the NotFound template, so if an item is not found, the user can easily create new item. If onclick is changed with onmousedown the button won't work. Another downside of this solution would be that when the user pushes the mouse button, the item would be immediately selected, which is not how buttons usually work - usually you are able to push the button, move the mouse to the side and release the button, which will result in no button click.
Another solution would be increasing the delay from 200 to 500ms - the item selection will work as expected - when the user selects an item, the items list will hide immediately, but if an user clicks outside of the items list he has to wait 500ms, which is not perfect, but not bad at the same time, and probably many users wouldn't even notice it. With this solution a button in the NotFound template will work as expected.
Please tell me which solution you prefer and I'll create a pull request.

**Comment by chrissainty** [comment]
@x6060x What was the code you used with the `event.PreventDefault()` and `onMouseDown`? I've been playing with some ideas this moring using JavaScript but it just keep nagging at me that somehow it's the overall design of the component that is wrong. I just can't figure out why.

**Comment by x6060x** [comment]
@chrissainty According to this [article](https://visualstudiomagazine.com/articles/2020/01/27/suppressing-events-blazor.aspx) using:
```csharp
@onmousedown:preventDefault
```
in the input control should work, but it didn't resolve the issue for me. I haven't tried calling js with JsInterrop.

**Comment by chrissainty** [comment]
But wouldn't we want the prevent default on the item in the suggestion list? As that is the element receiving the click? But that won't prevent focus being lost from the `input` which is what is causing the list to close in the first place.

**Comment by x6060x** [comment]
@chrissainty Sorry, my bad.. I had to re-read what I wrote, before posting. What you're saying is what I tried - I used the preventDefault on the items in the suggestions list, not in the input.

**Comment by ghok-rgb** [comment]
@chrissainty if i downgrade from 4.1.3 to 3.1.8 would there be any issues. I did not experience this issue in 3.1.8 so I am hoping I can downgrade without any issues. Could you please confirm that? Target framework for my application would be .NET Core 3.1

**Comment by chrissainty** [comment]
@ghok-rgb I would try it and see, I haven't tested the older versions with newer versions of Blazor.

**Comment by x6060x** [comment]
@ghok-rgb @chrissainty I haven't run version 3.1.8, but browsed the source code from 25th of Sept (when 3.1.8 was released) and onblur wasn't used back then - there was "addFocusoutEventListener" in the js file instead.

**Comment by chrissainty** [comment]
@ghok-rgb @x6060x I've been working on this most of the afternoon and evening and I've managed to remove all but one of the `Task.Delay`s, can probably get rid of the other one as well, just havn't tried yet.

Could either of you try the code in this branch and see if it's working as you expect. It needs more polishing before a PR but I think it's doing what we want.

**Comment by ghok-rgb** [comment]
@chrissainty sorry for getting back so late. I downgraded to 3.1.8 as a workaround. I am definitely going to try your latest branch and let you know sometime this weekend or next week. Thank you for spending time on this.

**Comment by x6060x** [comment]
@chrissainty For me the control is working as expected - I'm able to select an item from the list and click a button, which is located in the footer. However I noticed that I'm getting an error in the console:

TypeError: element.classList is undefined[Learn More] blazored-typeahead.js:55:13
    addOnClickListener https://localhost:44304/js/Blazored.Typeahead/blazored-typeahead.js:55

This is for both Firefox and Chrome.

**Comment by chrissainty** [comment]
@x6060x Thanks for the feedback. I’ll take a look this morning and see where that’s coming from and get it fixed.

**Comment by chrissainty** [comment]
I believe this has been resolved, I just seemed to have not linked the PR, so I'm going to close.
