### ISSUE TITLE
[Question] How to prevent multiple threading issue when searching from entity framework dbContex

### ISSUE THREAD

**Issue by adopilot** [Blazored/Typeahead#129]
I am trying to make Typeahead control searching from entity framework database.
My search metold looks like

```
private async  Task<IEnumerable<Something>> GetSomething(string searchText)
        {
         return await dbContex.Something.Where(x=> x.key.Contains(searchText)).ToListAsync();
        }
```

Sometime when db is slowly to preform search and if user while one searching task is started continue typing and trigger control to preform new search EF will rise exception

> System.InvalidOperationException: 'A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext

Is there a way to silently swallow this exception or to make searching sync.

I did try to increase Debounce param but this unnecessary put users on hold for first search.

There is also an idea to make control do search on key Enter stroke but I am not sure how to subscribe on key-events.

**Comment by chrissainty** [comment]
Hi @adopilot, you could get around this issue by adding something like an `IsSearching` bool around you DB context code. Then if subsequent calls come into your method you can ignore them until the current one finishes.

```csharp
private async  Task<IEnumerable<Something>> GetSomething(string searchText)
{
    if (!isSearching)
    {
        isSearching = true;
        var result = await dbContex.Something.Where(x=> x.key.Contains(searchText)).ToListAsync();
        isSearching = false;
        return result;
    }
}
```

I would also take a look at improving the performance of your DB query.

**Comment by chrissainty** [comment]
I'm guessing this answered your issue so I'm going to close.
