### ISSUE TITLE
[Question] Invalid HTML attribute in rendered control

### ISSUE THREAD

**Issue by dhebbler** [Blazored/Typeahead#131]
Thank you for all your work on the Typeahead component.  We have an application that is heavily form focused and makes use of tons of look-up / drop downs for data entry.  This control and the ability to easily wire it up to our existing framework is saving us months of work developing our own component.  It is also a lot more efficient than any other 3rd party components available.

We are noticing invalid HTML attributes included as part of the rendered Blazored Typeahead control.  This is causing failures in our performance tests using Ignitor.  Our test is a simple render page and navigation.  We are not interacting with the Blazored Typeahead component as part of the test.  Including the component in our page causes the navigation to fail. Removing the component from our page allows the Ignitor navigation to succeed.

Our Ignitor tests fail to navigate, but we don't get an exception or error message.  Our user testing with real browsers and our Selenium integration tests, including those that exercise the Blazored Typeahead component all succeed.  So it seems that our failing tests are more particular about the HTML structure. 

We noticed the following when inspecting the HTML in Chrome.

```
<div class="blazored-typeahead__controls">
<!--!-->
  <input autocomplete="off" type="text" 
     class="blazored-typeahead__input " _bl_235207c5-df70-4d1e-a078-131348b8cf0d>
<!--!-->
<!--!-->
<!--!-->
</div>
```

**_bl_235207c5-df70-4d1e-a078-131348b8cf0d**
This attribute will also appear on the blazored-typeahead__input-mask element after selecting an item.

Attributes with the _bl_ pattern appears to have something to do with Blazor's diff, frames, and element reference capture.  I've added a couple links below that might be relevant.  I didn't see anything in the Blazored Typeahead code that intentionally added the attribute.

I verified that this HTML attribute wasn't a side effect of something in our Blazor application or architecture. I created a simple project using just the basic Blazor Server-Side template and the example code from https://chrissainty.com/getting-started-with-blazored-typeahead/ .  The HTML shown above was taken from that sample project.  

**Ignitor**
Ignitor is a custom tool built by the Microsoft Blazor team to perform scale-out testing.  This tests larger loads than we can afford to do with Selenium Grid, 10k's -100k's concurrent connections.  I don't know if this is readily available or needed to help troubleshoot the issue.  I will reach our to our Microsoft contact to see if I can share it. 

Notes:

I've only done a little research trying to find the source of the attributes, but I've included a couple of thinks I located in the Blazor source that might help.

Typescript methods dealing with Capture Id like bl_${referenceCaptureId}

https://github.com/dotnet/aspnetcore/blob/291ad25f5d1107200f99380e979e3e8e42798b44/src/Components/Web.JS/src/Rendering/ElementReferenceCapture.ts

Typescript method insertFrame, case FrameType.elementReferenceCapture mentions 

> A "capture" is a child in the diff, but has no node in the DOM_

https://github.com/dotnet/aspnetcore/blob/4310fa72f7e94ffa8000bcdfee13053277dcda5f/src/Components/Web.JS/src/Rendering/BrowserRenderer.ts

I've included a ZIP of my example project.
[BlazoredTypeaheadExample.zip](https://github.com/Blazored/Typeahead/files/4566551/BlazoredTypeaheadExample.zip)

**Comment by chrissainty** [comment]
Thank you for such a detailed account @dhebbler.

The code that's causing your issue is generated by Blazor `@ref` directive. We use it to capture references to certain HTML elements we pass to JavaScript. Without these, the control won't function.

It seems odd that Ignitor would see this as a fail as it's code generated by Blazor itself. Unfortunately, I can't see there is anything we can do to alter the component. I think the best course of action is to check on Ignitor and understand why it's failing Blazors own code.

**Comment by dhebbler** [comment]
Thank you.  That helps me narrow down the code.  With this I can reproduce my issue with just a simple page and input with @ref.  

We've been using the @ref directive only with Blazor Component instances, and I've been passing string Ids to my JSInterop calls, then finding the element to interact with.  Passing the ElementReference is a lot cleaner, and I'll be updating my code to take advantage of these.  I'll reach out to our Microsoft contact to help us update Ignitor to handle these correctly.

Thank you again!
