### ISSUE TITLE
[Question] How do I make this field required in HTML5?

### ISSUE THREAD

**Issue by kirk-mcneil** [Blazored/Typeahead#133]
Hi Chris and Blazored team,
Hope you're all doing well in these odd times.
I'm using the type ahead as a component in an MVC form that fills out a hidden field and would like to make the field required. I tried making the object required in the component using data annotations but that doesn't help stop the form from getting submitted when it's empty.
Should I use javascript on it?
Thanks,
Kirk

**Comment by chrissainty** [comment]
Hi, I'm not sure the component will work correctly in that scenario. It's designed to be used in Blazor apps and with the Blazor mechanisms for form validation and submission.

I think you'll have to create some kind of manual solution for you use case.

**Comment by kirk-mcneil** [comment]
That's what I was afraid of. I'll build something to manually check it - thanks for the quick response!

**Comment by chrissainty** [comment]
One thing to try @kirk-mcneil is adding the HTML5 required attribute to the component and seeing what happens. We pass a few HTML attributes to the internal input control and I think required would get passed as well. Might be worth seeing what it does.
