### ISSUE TITLE
Is there a way i can use Z-Index , please see screenshot the issue i have

### ISSUE THREAD

**Issue by aqkhana2002** [Blazored/Typeahead#134]
**Please be sure to check the readme file before raising an issue.**
![image](https://user-images.githubusercontent.com/5283983/81234071-662e4500-903b-11ea-886d-2736148188c8.png)

is there a way I can use z-index

**Comment by chrissainty** [comment]
I’m sorry, but you need to be a more specific about what you’re asking.

**Comment by aqkhana2002** [comment]
if you look at the image i have attached you will notice dropdown is cut half if we have z-index option this might come front.  this had to display 10 items

**Comment by chrissainty** [comment]
Ah ok, as the image itself is cropped to where the suggestion list is cut off it makes it hard to spot.

If you want to affect the z-index you can do so by overriding the current settings via CSS. Just specify whatever new z-index you wish for this class, `.blazored-typeahead__results`.
