### ISSUE TITLE
[Bug] When disabled, dropdown icon shouldn't show unless EnabledDropDown is true

### ISSUE THREAD

**Issue by pelshen** [Blazored/Typeahead#139]
**Describe the bug**
If you don't have EnableDropDown set to true, when the field is rendered normally (Disabled is false), you do not get a dropdown arrow icon at the end. If you set Disabled to true, in the disabled version, you do get the icon.

**To Reproduce**
Use a BlazoredTypeahead without EnabledDropDown specified, or set to false explicitly. Set Disabled to true.

**Expected behavior**
A disabled field, with no icon.

**Screenshots**

**Hosting Model (is this issue happening with a certain hosting model?):**
N/A

**Additional context**
It's clear from BlazoredTypeahead.razor why this happens. Inside `if (Disabled)` the icon is always rendered but outside of that if/else there is `@if (!Disabled && EnableDropDown)` with the icon again. I would suggest the first should be removed completely, the `!Disabled` condition removed from the second one with disabled classes added conditionally. But then some other means would be needed to keep the height.

**Comment by chrissainty** [comment]
Thanks for reporting this @pelshen. It's definitely something we should fix.

**Comment by Webreaper** [comment]
I hit this, and was able to work around it by adding this in my CSS to just hide the down icon whenever the control is disabled. 

```
.blazored-typeahead__input-mask-wrapper--disabled {
    height: 28px;
}

.blazored-typeahead__input-icon--disabled ,
.blazored-typeahead__input-icon--disabled:hover {
    display: none;
}
```
