### ISSUE TITLE
Server Side Blazor preview 6

### ISSUE THREAD

**Issue by mikes-gh** [Blazored/Typeahead#14]
You probably know this already but you can now include static assets in a library which would eliminate a big caveat mentioned in the README

https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/

**Comment by chrissainty** [comment]
Hi Mike, unfortunately this is only for server-side Blazor projects.

Going forward Razor class libraries will be the way to go for sharing
Components and the Blazor class library will die off. But right now Razor
class libs don’t work with client-side Blazor.

So it’s swings and roundabouts. I spoke to Dan Roth about this the other
day and he said they’re hoping to have it sorted soon.

**Comment by mikes-gh** [comment]
Hi Chris

I had a good look round aspnetcore on github and found it difficult to get any info on this.
Is it this issue?

https://github.com/aspnet/AspNetCore/issues/7536

**Comment by chrissainty** [comment]
Hi Mike,

This is the issue is keep an eye on https://github.com/aspnet/AspNetCore/issues/10986

**Comment by mikes-gh** [comment]
Here’s another good reference https://github.com/aspnet/AspNetCore.Docs/issues/12884.  Looks like preview 9 is the target for RCL to cover client and server scenarios .  I feel like I hyjacked your repo for general discussion so feel free to close this.

**Comment by chrissainty** [comment]
No worries @mikes-gh 😄
