### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Kylar182** [Blazored/Typeahead#140]
**Is your feature request related to a problem? Please describe.**
Id and tabindex cannot be used to target input, the wrapper or something is blocking them possibly?

**Describe the solution you'd like**
Be able to tab to input and / or target input with id attribute

**Describe alternatives you've considered**
I've tried both id and tabindex, I know of no other way to programmatically select an input

**Additional context**
The idea is to allow the user to tab through inputs or focus the next input when the previous one is focused out as there is no way to navigate without touch or mouse input now

**Comment by chrissainty** [comment]
Hi @Kylar182, as far as I can see tabbing through the control works as expected. We did some work to enable this a while ago. You shouldn't need to add any additional attributes to allow this either.

Can you create a minimal repro of the behaviour you're seeing and we can take a look.

**Comment by Kylar182** [comment]
> Hi @Kylar182, as far as I can see tabbing through the control works as expected. We did some work to enable this a while ago. You shouldn't need to add any additional attributes to allow this either.
> 
> Can you create a minimal repro of the behaviour you're seeing and we can take a look.

You can tab through the controls while in the component, from outside the component it's not possible as the input is marked as hidden unless it's clicked on

**Comment by chrissainty** [comment]
@Kylar182 yes this is per design. The input is hidden as we display the selected template when the component doesn’t have focus. As soon as it has focus the selected template is hidden and the input is shown and focus is set to it automatically.

**Comment by Kylar182** [comment]
@chrissainty How do you focus the element? I attempted to add an id attribute but it was hidden with the input. What element should I focus to make the input available? Again, it's just for a user to be able to tab between inputs for quick inputs.

**Comment by chrissainty** [comment]
As I said earlier, you don’t need to do anything tabbing works out of the box. You can see this for yourself by running the sample projects in the repo.

**Comment by Kylar182** [comment]
Ahh, I see now. It works when you don't have tabindex set on any other form inputs or anywhere else out of the page and you can't use Id to set focus. Okay, fair enough, not for me I suppose.

**Comment by chrissainty** [comment]
Could you add your form code so I can see what you’ve done? I think I might be understanding what you’re trying to do but just want to check.

**Comment by Kylar182** [comment]
> Could you add your form code so I can see what you’ve done? I think I might be understanding what you’re trying to do but just want to check.

Technically it's a private repo with a contract attached, I'll mock something up and send it later today on a public one

**Comment by chrissainty** [comment]
As this has been almost a month with no updates I'm going to close this issue.

**Comment by Kylar182** [comment]
Hey @chrissainty I apologize, I've gotten pretty busy. Basically I can't focus the element via the ID or tabindex. My elements were all in child components though, not sure that matters. I appreciate the response though and sorry I didn't get a chance to push a repo.

**Comment by chrissainty** [comment]
No worries @Kylar182. I very much appreciate having a busy schedule
