### ISSUE TITLE
Microsoft.JSInterop.JSException: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by ghok-rgb** [Blazored/Typeahead#141]
Hello,

I am noticing this error when someone begins loading a page with typeahead control and navigates away from that page prematurely. Could you please let me know if you have seen this before and if no, how I can handle this? Any pointers will be much appreciated!

`Microsoft.JSInterop.JSException: Cannot read property 'addEventListener' of null
TypeError: Cannot read property 'addEventListener' of null
    at Object.addFocusoutEventListener (http://localhost:32666/_content/Blazored.Typeahead/blazored-typeahead.js:7:17)
    at http://localhost:32666/_framework/blazor.server.js:8:31421
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (http://localhost:32666/_framework/blazor.server.js:8:31390)
    at http://localhost:32666/_framework/blazor.server.js:1:19202
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (http://localhost:32666/_framework/blazor.server.js:1:19173)
    at e.processIncomingData (http://localhost:32666/_framework/blazor.server.js:1:17165)
    at e.connection.onreceive (http://localhost:32666/_framework/blazor.server.js:1:10276)
    at WebSocket.i.onmessage (http://localhost:32666/_framework/blazor.server.js:1:38091)
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at Blazored.Typeahead.BlazoredTypeaheadBase`1.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)`

`<BlazoredTypeahead SearchMethod="@SearchItems" @bind-Value="@SelectedItems" MinimumLength="3">`

UPDATE: I looked at the source code for javascript and here is where it is causing the issue:

`
window.blazoredTypeahead = {
    assemblyname: "Blazored.Typeahead",
    setFocus: (element) => {
        element.focus();
    },
    addFocusoutEventListener: (element) => {
        **element**.**addEventListener**("focusout", (event) => {
            if (element.contains(event.relatedTarget)
                || event.target.className == "blazored-typeahead__input-mask") // workaround relatedTarget bug
            {
                return; // don't react to this since it's a child.
            }
            DotNet.invokeMethodAsync(blazoredTypeahead.assemblyname, "OnFocusOut");
        })
    },
        // No need to remove the event listeners later, the browser will clean this up automagically.
    addEscapeEventListener: (element) => {
        element.addEventListener('keydown', (event) => {
            const key = event.key;
            if (key === "Escape") {
                DotNet.invokeMethodAsync(blazoredTypeahead.assemblyname, "OnEscape");
            }
        });
    }
}

So, it appears that if I switch between pages that have typeahead controls really fast, I am experiencing this error. Is the "element" null and it is trying to add eventlistener to a null element? Is there a way I can resolve it by myself?
`
Thanks for any pointers!

**Comment by chrissainty** [comment]
Hi @ghok-rgb, thanks for raising this.

There isn't anything you can do to resolve this yourself, we need to add a null check before adding the event listener. I'll mark this as a bug and we'll get this added in as soon as we can.

**Comment by chrissainty** [comment]
For reference this issue is here:

```javascript
addKeyDownEventListener: function (element) {
        element.addEventListener('keydown', function (event) {
            var key = event.key;

            if (key === "Enter") {
                event.preventDefault();
            }
        });
    }
```

we need to add a check for null before adding the event listener.

```javascript
addKeyDownEventListener: function (element) {
    if (element) {
        element.addEventListener('keydown', function (event) {
            var key = event.key;

            if (key === "Enter") {
                event.preventDefault();
            }
        });
    }
}
```
