### ISSUE TITLE
[Question] Cascading Typeahead Initial Value

### ISSUE THREAD

**Issue by tkennedy13** [Blazored/Typeahead#144]
I have a set of cascading typeahead. I'm using ValueChanged of the "parent" typeahead to load the data for the "child" typeahead. This part has worked well. The problem is when I open a record to edit it the "parent" typeahead is always empty even though there is a value stored for it in the database. The trouble has to do with my bindings i'm sure, but I am unable to use a binding value with ValueChanged. How else can I populate the "parent" typeahead?

Here is how the typeaheads are configured.

This is the parent:
```
<BlazoredTypeahead SearchMethod="SearchCountries" ValueChanged="@( (Country s) => SelectedCountryChanged(s) )"
			   ValueExpression="@( () => School.Country )"
			   TItem="Country" TValue="Country" EnableDropDown="true">
<SelectedTemplate Context="country">
	@country.Name
</SelectedTemplate>
<ResultTemplate Context="country">
	@country.Name
</ResultTemplate>
<NotFoundTemplate>
	Nothing Found
</NotFoundTemplate>
</BlazoredTypeahead>                     
```
and this is the child:
```
<BlazoredTypeahead SearchMethod="SearchRegions"
				   @bind-Value="School.Region" EnableDropDown="true">
	<SelectedTemplate Context="region">
		@region.Name
	</SelectedTemplate>
	<ResultTemplate Context="region">
		@region.Name
	</ResultTemplate>
	<NotFoundTemplate>
		Nothing Found
	</NotFoundTemplate>
</BlazoredTypeahead>
```

Thanks for your help with this.

**Comment by chrissainty** [comment]
Hey @tkennedy13, it looks like you're missing assigning the `Value` parameter. That is what assigns an initial value to the component.

```razor
<BlazoredTypeahead SearchMethod="SearchCountries" 
                                   Value="School.Country"
                                   ValueChanged="@( (Country s) => SelectedCountryChanged(s) )"
                                   ValueExpression="@( () => School.Country )"
                                   TItem="Country" TValue="Country" EnableDropDown="true">
<SelectedTemplate Context="country">
	@country.Name
</SelectedTemplate>
<ResultTemplate Context="country">
	@country.Name
</ResultTemplate>
<NotFoundTemplate>
	Nothing Found
</NotFoundTemplate>
</BlazoredTypeahead>      
```

**Comment by chrissainty** [comment]
I'm assuming as there has been no further comment that this resolved the issue so I'm going to close this. Feel free to reopen and provide extra detail if this is not the case.

**Comment by tkennedy13** [comment]
Sorry for the late reply. I got caught up in a different problem.

This worked great though! Thank you very much for the help.
