### ISSUE TITLE
Is there a Selected Item change Event ?

### ISSUE THREAD

**Issue by nssidhu** [Blazored/Typeahead#147]
Trying to build cascading Drop downs for Country/State/City.
Need to filter State Drop Down if Country is changed.
Is there an event that i can subscribe to or listen to for Typeahed  ?

**Comment by NatanBagrov** [comment]
Personally, I did not find any. I ended up writing a wrapper (for the dto) myself, providing the necessary events.

**Comment by chrissainty** [comment]
Hey @nssidhu, yes you can achieve this using the `ValueChanged` event. I've included some code to give you an example of how to configure it. You will need to provide the additional parameters as per the example code.

```razor
<BlazoredTypeahead SearchMethod="SearchCountries" 
                                   Value="Model.Country"
                                   ValueChanged="@( (Country s) => SelectedCountryChanged(s) )"
                                   ValueExpression="@( () => School.Country )"
                                   TItem="Country" TValue="Country" EnableDropDown="true">
    <SelectedTemplate Context="country">
        @country.Name
    </SelectedTemplate>
    <ResultTemplate Context="country">
        @country.Name
    </ResultTemplate>
    <NotFoundTemplate>
        Nothing Found
    </NotFoundTemplate>
</BlazoredTypeahead>      
```

The example here is taken from a similar question #144. Let me know if you have any problems.

**Comment by nssidhu** [comment]
> ```
>  ValueChanged="@( (Country s) => SelectedCountryChanged(s) )"
> ```



> Hey @nssidhu, yes you can achieve this using the `ValueChanged` event. I've included some code to give you an example of how to configure it. You will need to provide the additional parameters as per the example code.
> 
> ```
> <BlazoredTypeahead SearchMethod="SearchCountries" 
>                                    Value="Model.Country"
>                                    ValueChanged="@( (Country s) => SelectedCountryChanged(s) )"
>                                    ValueExpression="@( () => School.Country )"
>                                    TItem="Country" TValue="Country" EnableDropDown="true">
>     <SelectedTemplate Context="country">
>         @country.Name
>     </SelectedTemplate>
>     <ResultTemplate Context="country">
>         @country.Name
>     </ResultTemplate>
>     <NotFoundTemplate>
>         Nothing Found
>     </NotFoundTemplate>
> </BlazoredTypeahead>      
> ```
> 
> The example here is taken from a similar question #144. Let me know if you have any problems.

I keep on getting this error.
since this is the first load of Page, i cant set any value.
Also i am not sure what is the use of   ValueExpression is it trying to over come the null problem ?
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Value cannot be null.
      Parameter name: accessor
System.ArgumentNullException: Value cannot be null.
Parameter name: accessor
  at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.Create[TField] (System.Linq.Expressions.Expression`1[TDelegate] accessor) <0x3a28a70 + 0x00016> in <filename unknown>:0 
  at Blazored.Typeahead.BlazoredTypeahead`2[TItem,TValue].OnInitialized () <0x3a20930 + 0x0015a> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x3656b40 + 0x00030> in <filename unknown>:0 
```

I don't get error when i use @bind-Value, only when i change it to Value.
How do i handle this ?
 <BlazoredTypeahead SearchMethod="SearchBusiness"
                                       Value="_SelectedOrganization"
                                       ValueChanged="@( (GetInLine.Shared.DbModels.Organization s) => SelectedOrgnaiztionChanged(s) )"
                                   
                                       Debounce="500">
                        <SelectedTemplate Context="org">
                          @org.OrgCode
                        </SelectedTemplate>
                        <ResultTemplate Context="org">
                            <div class="row">
                                <div class="col col-auto">@org.OrgName</div>
                                <div class="col col-auto">@org.Address1  @org.Address2 </div>
                                <div class="col  col-auto">@org.CityName ,  @org.StateName , @org.CountryName</div>
                            </div>
                         
                        </ResultTemplate>
                        <NotFoundTemplate>
                            Sorry, there weren't any search results.
                        </NotFoundTemplate>
                    </BlazoredTypeahead>

**Comment by nssidhu** [comment]
I have tried to create sample in the attached file(webAssembly Index Page at the bottom).
Will appreciate your help in getting it working.

[Typeaheadchanged.zip](https://github.com/Blazored/Typeahead/files/4984153/Typeaheadchanged.zip)

**Comment by chrissainty** [comment]
By the looks of your code you've not included the ValueExpression as per my example in my last comment. You need all 3, Value, ValueChanged and ValueExpression.
