### ISSUE TITLE
[Question] MaximumSuggestions default value

### ISSUE THREAD

**Issue by NatanBagrov** [Blazored/Typeahead#148]
Hi, just something I have encountered in my application and might worth consideration.

The default value is not UX-ish, it is rather too small.
#### Why?
When writing the code, developers might overlook this `MaximumSuggestions=10` default value, limiting the max suggestions to 10.

Since users are using the list, they might think that there are no *additional* results, since nothing is written (i.e. "Showing 10 of 42 results. Please rephrase your search").

This will cause the users to type additional character (hopefully to provide less than or equal to 10 results), or just assume that what they are after is really not in the list...

I understand that this is a minor "dear developer, use your eyes", but I think this "default path" should be the one that "just works as expected".

#### A possible solution
Either set the default limit to max elements or provide some info that this is partial suggestion list.
I think the combination works best - this will allow the developer to *actively optimize* if needed, and will "guard" this optimization with an information to the user.

Cheers!

**Comment by chrissainty** [comment]
Hi @NatanBagrov, 

Thanks for asking this question 🙂.

There are options available to the developer to control this. As you pointed out, there is the `MaximumSuggestions` parameter. There is also a footer template which can be used to add a message as you have suggested, prompting the user to type more characters.

I appreciate where you're coming from with this, but the tools are already there. In my opinion a library should not make too many presumptions. 

I hope you this all makes sense but this isn't something we'd look to change at the moment.

**Comment by NatanBagrov** [comment]
Sure @chrissainty , no worries. I agree that it everything that is needed is indeed there.

Just wanted to share my experience regarding the default value, I ended-up changing it across the app since I've overlooked it when I started using the component. :)
