### ISSUE TITLE
[Bug] Typeahead Erasing Keystrokes when in a Blazored Modal

### ISSUE THREAD

**Issue by ericpincus** [Blazored/Typeahead#149]
I just upgraded to the new version of Blazored Modal (including the new setup that includes adding a script file to index.html). I have Typeahead controls in various Blazored Modals and they all immediately erase any keystrokes. For example, I can type in the letter "s" and for a moment I can see it, but then it's erased. I can't get to the second character.

To test, I pulled the same code out of a modal and put it into a general view page and it works as expected.

Using Blazor WebAssembly (Hosted)

Here's my code:
` <BlazoredTypeahead SearchMethod="@SearchPlayers" MinimumLength="3"
                                   @bind-Value="@Player" Debounce="500">
                    <SelectedTemplate>
                        @context.FullName
                    </SelectedTemplate>
                    <ResultTemplate>
                        @context.FullName
                    </ResultTemplate>
                    <NotFoundTemplate>
                        None found.
                    </NotFoundTemplate>
                </BlazoredTypeahead>
`

in the code section

 `  private PlayerSimple Player;
    private async Task<IEnumerable<PlayerSimple>> SearchPlayers(string searchText)
    {
            return await Http.GetJsonAsync<IEnumerable<PlayerSimple>>($"api/[REDACTED]/{searchText}");
    }`

The exact same code works as expected, outside of a Blazored Modal.

Thank you.

**Comment by ericpincus** [comment]
FWIW: Adding StopPropagation = "true" seems to resolve whatever the issue is within the BlazoredModal.

**Comment by chrissainty** [comment]
@ericpincus Thanks for raising this. Where about did you add the StopPropagation directive? Could you provide a code sample?

**Comment by ericpincus** [comment]
Sure thing:

Everything after the opening tag is identical as above, here's the revised BlazoredTypeahead tag that gets around the issue:

`<BlazoredTypeahead SearchMethod="@SearchPlayers" MinimumLength="3"
                                   @bind-Value="@Player" Debounce="500" StopPropagation="true">`

**Comment by chrissainty** [comment]
This issue isn't actually a problem with Typeahead but with Modal and should be resolved with https://github.com/Blazored/Modal/pull/202. I'm going to close this issue as there is nothing to do.
