### ISSUE TITLE
Fill like a DropDownList

### ISSUE THREAD

**Issue by fnils** [Blazored/Typeahead#15]
Is there a way to use this like a DropDownList?
Example when I click on it all list items are shown and then I can filter them.

**Comment by chrissainty** [comment]
This isn't currently an option I'm afraid, but it could certainly be looked at as a new feature. 

I think there would need to be a limit set on the number of items to display, this currently doesn't exist. Then there would need to be some way of firing the search method with an empty search string. Let me have a think.

**Comment by fnils** [comment]
Sounds good! It could be an option that you can turn on if you need it. Then you don't have to limit the data that is shown.

**Comment by vertonghenb** [comment]
@chrissainty Any thoughts about this? 
Most of these type of components have their searchbar separated from the input like bootstrap select.
