### ISSUE TITLE
[Feature Request] Add a public method to focus the component

### ISSUE THREAD

**Issue by rvanderkooy** [Blazored/Typeahead#150]
**Is your feature request related to a problem? Please describe.**
I'm trying to find a way to programmatically expand the result dropdown list  

**Describe the solution you'd like**
I would like to see a public method that can be called that will focus the input box and expand the dropdown list

**Describe alternatives you've considered**
I have tried to set focus using JSInterop to see if that would trigger it, with no luck.

**Additional context**
I have a bootstrap modal that contains the Typeahead control along with Save and Cancel buttons. I'm trying to have the Typeahead control expand when the modal opens.

**Comment by chrissainty** [comment]
I think the way we could offer this would be a public method on the component called `Focus`, for example. You can then get a reference to the component using the `@ref` directive then just invoke `Focus`.

**Comment by rvanderkooy** [comment]
A public Focus method would be great. I’d be glad to help however I can. Thanks.

**Comment by Kylar182** [comment]
https://github.com/dotnet/aspnetcore/issues/17472#event-3572453000

**Comment by arivera12** [comment]
did you try passing the `autofocus` attribute on the input?

**Comment by kiasyn** [comment]
I have submitted a pull request that implements this functionality... https://github.com/Blazored/Typeahead/pull/166
