### ISSUE TITLE
Dropdown icon on Internet Explorer not Working

### ISSUE THREAD

**Issue by suryasundarraj** [Blazored/Typeahead#153]
**Describe the bug**
The drop down icon is working fine on Firefox, but on IE 11 there the drop down opens only when you click on top of the icon

**To Reproduce**
1. Go to MS IE 11 with a sample app using typeahead with enabledropdown
2. Click on border box of the arrow, it works
3. Clicking on the down arrow box has the issue

**Expected behavior**
The user should be able to click on the icon to see drop down items 

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

Please help me out to fix this issue, Thanks in advance

**Comment by chrissainty** [comment]
Thanks for reporting this @suryasundarraj. Unfortunately, I'm now running exclusively on a mac and I can't run IE11.

This will have to be a contribution for you, or the community.

**Comment by PatriciaHeimfarth** [comment]
Hi, I would like to work on that issue

**Comment by chrissainty** [comment]
Closing as we're not going to support IE11 anymore.
