### ISSUE TITLE
[Feature Request] What about supporting internally this parameters: Hide, Hidden and ReadOnly?

### ISSUE THREAD

**Issue by arivera12** [Blazored/Typeahead#154]
Hide -> Hide the component using razor syntax like this `@if(!Hide) { }`
Hidden -> Hide the component via style sheet like this `style="@(Hidden ? "display:none": "")"`

Take note that hide and hidden are not the same and also doen't behave the same. 

Hide will destroy the component while hidden will not destroy it and hide it via style.

ReadOnly -> Makes the input readonly.

I know we can pass extra parameter but when we come to use all this properties outside the component comes more difficult to maintain.

It would be cool to hide any component internally rather than outside of it.

**Comment by chrissainty** [comment]
Hi @arivera12 this isn't something we would support in the component. Developers can hide the component with normal razor code when required.

**Comment by arivera12** [comment]
The point was its more clean and clear on UI having this `Hide=true` than `@if(Hide) { }`
