### ISSUE TITLE
[Feature Request] onchange?

### ISSUE THREAD

**Issue by AskYous** [Blazored/Typeahead#158]
**Describe the solution you'd like**
I use this typeahead in a child component, and the parent component needs to be notified of the change. Binding to a value does cause the state to change, but not the parent component to change. We need something like `onchange` so I can invoke a parent listener.

**Describe alternatives you've considered**
Using the property `ValueChanged` but that caused errors.

**Comment by chrissainty** [comment]
ValueChanged is the correct way to do what you're looking to achieve. We won't be adding anything additional to the component for this. If you shared the errors you're getting hopefully we can spot what's not right with you're approach.

**Comment by AskYous** [comment]
#### `ValueChanged` without `@bind-value`

Code:
```razor
<BlazoredTypeahead TValue="QnADTO"
                   TItem="QnADTO"
                   SearchMethod="SearchMethod"
                   ValueChanged="newVal => onchange.InvokeAsync(newVal)">
```
Errors at runtime:

> [2020-08-16T18:08:54.931Z] Error: System.ArgumentNullException: Value cannot be null. (Parameter 'accessor')
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.Create[TField](Expression`1 accessor)
   at Blazored.Typeahead.BlazoredTypeahead`2.OnInitialized()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
---
#### `ValueChanged` with `@bind-value`

Code:
```razor
<BlazoredTypeahead TValue="QnADTO"
                   TItem="QnADTO"
                   SearchMethod="SearchMethod"
                   @bind-Value="selectedQnaSet"
                   ValueChanged="newVal => onchange.InvokeAsync(newVal)">
```
Error at compile time:
> Error RZ10010: The component parameter 'ValueChanged' is used two or more times for this component. Parameters must be unique (case-insensitive). The component parameter 'ValueChanged' is generated by the '@bind-Value' directive attribute. (RZ10010) (BotEditor)

**Comment by chrissainty** [comment]
You have to set several parameters when using ValueChanged directly. There are quite a few example of this in other issues but I would check out this one https://github.com/Blazored/Typeahead/issues/124#issuecomment-632421782

Also when using ValuesChanged you can't use @bind-Value as that is is using ValueChanged under the hood. It's an either, or situation.

**Comment by AskYous** [comment]
Thank you! I used `ValueExpression` and it worked! One thing I noticed though is that `ValueExpression` doesn't really do anything. I have the code below, but I never set `selectedQnaSet` to anything, and it still worked fine. I wanted to just remove `ValueExpression` but that gives the null exception mentioned earlier.

```razor
<BlazoredTypeahead TValue="QnADTO"
                   TItem="QnADTO"
                   SearchMethod="SearchMethod"
                   ValueChanged="newVal => {
                                     if (newVal == null) return;
                                     onchange.InvokeAsync(newVal);
                                 }"
                   ValueExpression="() => selectedQnaSet"> @* used here *@

@code {
    [Parameter] public EventCallback<QnADTO> onchange { get; set; }
    private QnADTO selectedQnaSet; // but never even initialized
}
```

**Comment by chrissainty** [comment]
Glad you've got it working :)
