### ISSUE TITLE
Server-side sample doesn't work on IIS Express

### ISSUE THREAD

**Issue by mikes-gh** [Blazored/Typeahead#16]
I was playing with the sample and noticed the server side blazor sample stops working after the first search when using IIS Express.  
I then found out websockets doesn't work on IISExpress 8 on windows 7. only on 8 or 2012+

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-2.2

Fortunately using Kestrel works fine.

Just in case anyone else was coming across the same issue.

Maybe a note in readme if using windows 7 use Kestrel?

**Comment by chrissainty** [comment]
Thanks for reporting this @mikes-gh. I assume this is effecting using server-side Blazor full stop then?

**Comment by mikes-gh** [comment]
Only iisexpress on windows 7.  I expect most are on windows 10 by now.  Easily worked around by using kestrel directly instead
