### ISSUE TITLE
[Feature Request] Custom Filter 

### ISSUE THREAD

**Issue by Treemendus** [Blazored/Typeahead#160]
Add the ability to use a custom filter search instead of having to select a value found in the search method.

**Comment by chrissainty** [comment]
Hi @Treemendus, could you clarify what you want in this request? You have full control over what the Search method returns, I'm not sure what more could be done.

**Comment by Treemendus** [comment]
I am trying to search the result set but be able to keep the typed texted as the input instead of it selecting the first matched result from the search method.

I am attempting to use this like a Google search that will allow partial searching as well as selecting the suggested text options.

I hope this clarifies my request more.

**Comment by chrissainty** [comment]
I *think* I have an idea what you mean. You want users to type a few characters into the typeahead, they then see some suggestions based on what's returned from the Search method. But they can still hit enter without selecting one of the results and that triggers another search? Is that right?

**Comment by Treemendus** [comment]
Yes that is exactly what I want.

**Comment by chrissainty** [comment]
No this isn't possible right now. I think this would be pretty difficult to fit into the control with it's current design, I'm also not sure if this is pushing the bounds of what a typeahead should be doing. At least what I would interpret as a typeahead control. 

I'd be interested in others feedback and thoughts on this, if it's popular we could look at what would be required to make it work.

**Comment by chrissainty** [comment]
I'm going to close this issue, mainly for the reasons I've mentioned in my comment above. There has been no further interest in the feature either. We can revisit at a later time if interest grows.
