### ISSUE TITLE
[Bug] StateHasChanged reset the component

### ISSUE THREAD

**Issue by RomainAn** [Blazored/Typeahead#161]
Hi everyone, i come to you because i have a little issue with the typeahead

**Describe the bug**
If the view get refresh while doing a typeahead, it cancel the suggestion and clear the input.

**To Reproduce**
1- Start doing an autocomplete
2- Trigger a refresh (For my case i use SignalR for realtime data update)

**Expected behavior**
 Do not refresh or reset the current typeahead even a StateHasChanged() occure.

**Hosting Model**

 - Blazor WebAssembly

Have a great day, and stay safe !

Edit : I managed to make is work by using an override in the parent component of the property ShouldRender.
But in my opinion, the component should take care of this, internally.

**Comment by chrissainty** [comment]
Hi @RomainAn, unfortunately this isn't a bug and this isn't something that we would be able to fix or do anything about. This is how Blazor functions and we can't override it, the best thing you can do is take advantage of ShouldRender as you have. 

Sorry we can't be more help on this one.
