### ISSUE TITLE
[Bug] Publish website failed to load dll

### ISSUE THREAD

**Issue by alexandredsimoes** [Blazored/Typeahead#164]
**Describe the bug**
My website published as win-x86 / stand-alone, shows an error loading the file "Blazored.Typeahead.dll"
Only the published site displays the error, locally the site runs smoothly

**To Reproduce**
1. Publish website as selfcontained/win-x86

**Expected behavior**
The site runs smoothly

**Screenshots**
![image](https://user-images.githubusercontent.com/5480346/91337185-60ef3480-e7a9-11ea-9a47-7ffc0b9e40ae.png)

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Comment by chrissainty** [comment]
I'm guessing from the error message the dll hasn't been included in the published output. Can you check to see if it's there?

**Comment by alexandredsimoes** [comment]
Its include.
![image](https://user-images.githubusercontent.com/5480346/91446062-54bcb300-e84d-11ea-9916-5af5b969c144.png)

**Comment by chrissainty** [comment]
I'm not sure on this one @alexandredsimoes. I think the only thing you can do is raise an issue on the Blazor repo and see what the team have to say. We have no way to effect any of this - at least as far as I'm aware.

**Comment by alexandredsimoes** [comment]
Problem solved. I just removed everything and uploaded again. Don't blame me. 🤷‍♂️🤷‍♂️🤷‍♂️
