### ISSUE TITLE
Best practice for loading details upon selecting an item.

### ISSUE THREAD

**Issue by zandhaai** [Blazored/Typeahead#165]
I am confused what is the best practice for loading the details for a selected item. I am seeing issues which use the 'ValueChanged'  option. Isn't it viable to use the setter of a property bound to '@bind-Value?'

Example:

`    
  <BlazoredTypeahead SearchMethod="..."
                                       @bind-Value="@ SelectedItem">

@code {
   
    public string SelectedItem
    {
        get => _selectedItem;
        set
        {
            _selectedItem = value;
            if (value == null) return;

            TheDetails = AsyncUtil.RunSync(() => GetDetails(value));
        }
    }
}
`

**Comment by chrissainty** [comment]
@zandhaai You can do it however, you wish. You can either use `ValueChanged` or the setter of the bound property, the choice is yours'
