### ISSUE TITLE
[Question] How to trigger method when clicking the Clear "X" button?

### ISSUE THREAD

**Issue by sion-corn** [Blazored/Typeahead#167]
I have 2 lookaheads on a form: Country and City. The City lookahead triggers a sproc with a parameter that is based on the object that is bound to Country.

So, what I'd like to do is: when both Country and City are populated --> user clicks the Clear "X" button on Country lookahead --> City lookahead also gets cleared.

How would I do this? I was hoping to add a method that gets triggered when the Country lookahead Clear "X" button gets pressed, that would set the City-bound object to null.

**Comment by chrissainty** [comment]
There is no event we expose to hook onto for clearing the typeahead. One way you could achieve this is by using the setter of the property which is bound to the typeahead, when you clear the Country typeahead we reset the bound value to its default, when that happens you could then trigger a clear of the City typeahead. Does that make sense?

**Comment by sion-corn** [comment]
Yes, that makes sense - will do it that way. Thanks for your advice.

**Comment by sion-corn** [comment]
I implemented your suggestion, and it works great. The only issue I have now is that when the City typeahead is cleared, it does not show the `blazored-typeahead.valid.modified` formatting. Is there a way to trigger validation programmatically?

**Comment by chrissainty** [comment]
What class is the City Typeahead applying?

**Comment by sion-corn** [comment]
@chrissainty it's a custom class - see below:

public class City
    {
        public int Id { get; set; }
        public int RegionId { get; set; }
        public int RegionId2 { get; set; }
        public int CountryId { get; set; }
        public string Name { get; set; }
        public string SearchNameCity { get; set; }
        public decimal? Latitude { get; set; }
        public decimal? Longitude { get; set; }
        public long? Population { get; set; }
        public string Timezone { get; set; }
    }

**Comment by chrissainty** [comment]
@sion-corn Sorry, I meant which CSS class.

**Comment by sion-corn** [comment]
@chrissainty it's sitting in a bootstrap `input-group` div

**Comment by chrissainty** [comment]
Once again, sorry that's not what I meant. In you earlier comment you said the Typeahead didn't have the `blazored-typeahead.valid.modified` class. I was asking which class it does have. But I'm going to go ahead and guess that it doesn't have one at all perhaps? 

After you have cleared the Typeahead it is essentially reset, therefor it wouldn't show any validation as it doesn't have a value to validate.

**Comment by chrissainty** [comment]
Closing as due to inactivity/looks to be resolved.
