### ISSUE TITLE
[Feature Request] Support for Mobile Blazor Bindings

### ISSUE THREAD

**Issue by ktaze1** [Blazored/Typeahead#168]
**Is your feature request related to a problem? Please describe.**
Typeahead does not work in Web view of the Mobile Blazor Bindings

**Describe the solution you'd like**
Support for Blazored.Typeahead in webviews

**Comment by chrissainty** [comment]
Hi @ktaze1, could you provide some more detail on what's happening when you try and use the control?

I will point out now that Mobile Blazor Bindings is an experiment and not an official product, so we don't necessarily expect the component to work there. Also we would not make any changes to the component, at this stage, to support MBB.

**Comment by chrissainty** [comment]
Closing as no further communication.
