### ISSUE TITLE
[Feature Request] Add AllowClear optional parameter

### ISSUE THREAD

**Issue by sion-corn** [Blazored/Typeahead#169]
**Is your feature request related to a problem? Please describe.**
BlazoredTypeahead has no way to optionally remove/hide the Clear button.

**Describe the solution you'd like**
Add an AllowClear optional bool parameter that enables/disables the above feature.

**Comment by chrissainty** [comment]
Hi @sion-corn, I'm curious why would you want to remove the ability to clear the typeahead?

**Comment by sion-corn** [comment]
Hi @chrissainty, in my case, I am including I am using typeaheads as dynamically-added fields, and each one has a "remove" button next to it. So in my case, the clear button on the typeahead is redundant. Moreover, I don't think there is a way to extend your built-in clear method to have it include my own custom logic, so it would be nice to disable it. Even if I could write an extension method for your clear function, it would contradict the design language on my site, since my non-typeahead dynamically-added fields would still rely on the "remove" buttons next to them, so removing the typeaheads from a dynamically-generated group of inputs by clicking on your "X" icon (using an extended method) would look different than removing non-typeahead inputs from a dynamically-generated group of inputs.

**Comment by chrissainty** [comment]
@sion-corn So you would never want users to be able to clear the value in the Typeahead, they should only be able to remove the Typeahead entirely as per your UI design? Have I understood correctly?

**Comment by sion-corn** [comment]
@chrissainty I wouldn't say "never," as I am also using Typeaheads in parts of my forms that are not dynamically-generated, in which case the built-in clear button is useful. But having an option to disable(hide/remove) the built-in clear button would be useful  for cases where the UI is dynamically-generated. It would also be really helpful to include a custom ClearMethod to extend the "on clear" logic, if that's something you're open to.

**Comment by chrissainty** [comment]
Yeah, I think we can add a toggle to just hide the clear button.

**Comment by sion-corn** [comment]
@chrissainty nice, thanks!

**Comment by tofron** [comment]
![Screenshot 2020-12-28 15 43 58](https://user-images.githubusercontent.com/67416470/103201877-99ec1100-4923-11eb-85de-e16048f2e846.png)

Above Happen when i click the x clear button on right side. 

` <BlazoredTypeahead SearchMethod="SearchItem" @bind-Value="@Pilihan">
        <SelectedTemplate>
            @context.Nama_Item
        </SelectedTemplate>
        <ResultTemplate>
            @context.Nama_Item
        </ResultTemplate>
        <NotFoundTemplate>
            Tidak Ada Data Ditemukan.
        </NotFoundTemplate>
</BlazoredTypeahead>`

Beside the clear x, everything went smooth. Can you please make a feature to hide those clear button so user didn't catch any error

**Comment by chrissainty** [comment]
@tofron Could you please open a separate issue as what you've commented is not related to this feature request. But it looks like you've misconfigured your EditForm component as per the error, that isn't a problem with this library.

**Comment by tofron** [comment]
i get this error even when typeahead are not inside the EditForm. Everytime i click the clear x button. Other than that, Typeahead working perfectly fine
![tes](https://user-images.githubusercontent.com/67416470/103509809-8c400980-4e96-11eb-8eef-431142156589.png)

**Comment by chrissainty** [comment]
@tofron Please open a new issues. This issue is closed.
