### ISSUE TITLE
[Question] How to use ConvertMethod?

### ISSUE THREAD

**Issue by vborovikov** [Blazored/Typeahead#171]
If I'm displaying a list of ClientModel objects but want the selected value to be their ClientId property I thought have to use ConvertMethod. But then the control will display ClientId instead of their Name for the selected item which breaks usability of the control. 

So how am I supposed to use ConvertMethod in my scenario? I need to display ClientModel.Name everywhere but to bind to ClientModel.ClientId.

```razor
        <BlazoredTypeahead TItem="ClientModel" TValue="ClientId" @bind-Value="ClientId" SearchMethod="SearchClientsAsync" EnableDropDown="true" class="form-control" ConvertMethod="GetClientId">
            <SelectedTemplate>@context.Name</SelectedTemplate> @*syntax error here, context has ClientId type *@
            <ResultTemplate>@context.Name</ResultTemplate>
        </BlazoredTypeahead>
@code {
            public ClientId ClientId { get; set; }
            private static ClientId GetClientId(ClientModel client) => client.ClientId;
}
```

**Comment by chrissainty** [comment]
There is an example showing how to do exactly what you want in the sample project. Apologies, I'm answering from my phone so can't link directly to it but there is only one page in the sample project, so it's not hard to find.
