### ISSUE TITLE
Is there a limit on the number of Blazored typeaheads on one page?

### ISSUE THREAD

**Issue by zandhaai** [Blazored/Typeahead#176]
For my Angular 1 page, which I am converting to Blazor, I am having more than 5 Typeaheads on a form. Are there any risks in using more than Blazored Typeahead? Or should I use some smart re-use of 1 Blazored Typeahead component?

**Comment by chrissainty** [comment]
No, there shouldn't be anything for you to worry about. In the sample apps we have multiple Typeaheads on a single page.

**Comment by MohammadMrz** [comment]
I'm trying to use multiple BlazoredTypeahead on same page. 
Would you kindly show how to use many BlazoredTypeahead on the same page.

**Comment by zandhaai** [comment]
I'm having at least six without any problems.

`
           <div class="col-md-12" style="padding-bottom: 25px;">
                <div style="width: 60%; margin: auto;">
                    <BlazoredTypeahead SearchMethod="FindSomething"
                                       @bind-Value="@SelectedSomethingId"
                                       Debounce="300"
                                       MinimumLength="3"
                                       EnableDropDown="false"
                                       MaximumSuggestions="200"
                                       Placeholder="Search for something">
                        <SelectedTemplate Context="someId">
                            @someId
                        </SelectedTemplate>
                        <ResultTemplate Context="someId">
                            @someId
                        </ResultTemplate>
                        <HelpTemplate>
                            Type your help text here
                        </HelpTemplate>
                        <NotFoundTemplate>
                            Nothing found!
                        </NotFoundTemplate>
                    </BlazoredTypeahead>
                </div>
            </div>
`

This I repeat on the page with slightly variations.

**Comment by MohammadMrz** [comment]
Hi Zandaai
Thanks for posting your code. 
Can you post the code for another drop down list, so I can see how you distinguish between them. 
I'm experiencing problems with the @someId part. 

`                        <SelectedTemplate Context="someId">
                            @someId
                        </SelectedTemplate>`

I'm not sure how to tell blazored typeahead how to distinguish between the drop down lists. 
Thanks
