### ISSUE TITLE
[Bug] EditContext IsModified() is True when no change

### ISSUE THREAD

**Issue by brettwinters** [Blazored/Typeahead#179]
**Describe the bug**
IsModifed property of the EditContext shows true when no change. 

Conversely IsModified() is correct if there is a change or the selection is reset

**To Reproduce**
1. Using the Webassembly demo project, open index.razor
2. Add the following line to the bottom of the `OnInitialized()` method : `FormModel.SelectedPerson = People.First();`
3. Add the following razor code inside the EditForm `<p>@context.IsModified()</p>`
4. Run the project. 
5. Select the same Person, in this case it's "Martelle"
6. Note that the result displayed is True (should be false since there is no change)

**Expected behavior**
The EditContext should display IsModified == false when there is no change to the selection

**Screenshots**
![image](https://user-images.githubusercontent.com/26474006/97699243-7b4bd400-1ab2-11eb-94e3-eb953ad63cef.png)

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly (haven't tested server side)
 - Demo project

**Additional context**
I'm using the EditContext IsModified() to disable the submit button

**Comment by mohankumar91** [comment]
https://github.com/dotnet/aspnetcore/issues/28590
