### ISSUE TITLE
[Bug] Pressing backspace removes previously selected option, not only search text

### ISSUE THREAD

**Issue by Martin-Pucalka** [Blazored/Typeahead#186]
**Describe the bug**
When I use multiselect, select some option, then press one character to search another option and then I press backspace, the selected option is deleted with the character.

**To Reproduce**
Run sample app
Go to Blazored Typeahead - Multi-select
Select some option
Start new search for another option by pressing one character on keyboard
Press backspace.
The character and prevoiusly selected option are deleted both 

**Expected behavior**
I think, that only the last character should be deleted. Last selected option should be deleted on pressing backspace only when there is no character in search text, for example like in select2 (https://select2.org/getting-started/basic-usage, section Multi-select boxes)

**Screenshots**
-

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Additional context**
-

**Comment by chrissainty** [comment]
Hi @Martin-Pucalka - this issue was fixed in the latest release. What version of the package are you using?

**Comment by Martin-Pucalka** [comment]
Thank you for your reply, I've missed the latest release, now it works well.
