### ISSUE TITLE
[Bug]An entry that has already been selected must not be able to be selected a second time

### ISSUE THREAD

**Issue by Otto404** [Blazored/Typeahead#189]
Expectation: an entry that has already been selected cannot be added a second time.

Observation: An entry can be any number of times selected.
![image](https://user-images.githubusercontent.com/3367832/103148056-f56ba280-475b-11eb-868a-820010627e54.png)

**Comment by chrissainty** [comment]
@Otto404 Could you please provide a repro project showing this bug? I can't recreate it on my end.

For reference, when using the multi-select we do the following check when a value is selected:

```csharp
      if (valueList.Contains(value))
          valueList.Remove(value);
      else
          valueList.Add(value);
```

Could it be that your objects are not being considered equal hence the check is passing?

**Comment by dustinptg** [comment]
Implement IEquatable would fix it for me but it is difficult to implement IEquatable on every object especially I'm passing a generic T into it
