### ISSUE TITLE
[Bug]Typeahead SearchMethod is not invoked at last backspace

### ISSUE THREAD

**Issue by ThapaChandrika** [Blazored/Typeahead#190]
Bug :Typeahead SearchMethod is not invoked at last backspace(or selecting the text and backspace)

1. Type sth in typeahead field
2. Clear the field by backspace(or by selecting the text and pressing backspace)

Expected behaviour
All available dropdown options should be shown if all text is cleared

Before searching
![image](https://user-images.githubusercontent.com/22572147/103400293-b202a100-4b6c-11eb-9c18-3263b90083e2.png)

After typing something
![image](https://user-images.githubusercontent.com/22572147/103400365-ea09e400-4b6c-11eb-8dd7-4b56fec7a3b1.png)

After clearing text field by backspace
![image](https://user-images.githubusercontent.com/22572147/103400401-0574ef00-4b6d-11eb-9b11-a981e652369e.png)

**Comment by chrissainty** [comment]
Using the backspace key, deleting character by character, works as expected for me. However, I can replicate selecting the current input text and deleting with backspace - this does not reset the search results. There are two factors which are effecting this:

1. There is a check to see if the search text has at least one character before performing a search
2. The `MinimumLength` property allows developers to specify how many characters need to be typed before a search happens - defaulted to 1.

I think to resolve this we would need to remove the check on the search text length, however this introduces a difference issue in that certain configurations of the typeahead will always show their search suggestions list. 

At this point in time trying to solve this would create bigger issues and while I agree this isn't ideal behaviour, the moment the user starts typing again suggestions will be correctly populated. For now I'm going to close this as a won't fix but if this is requested by more developers we can reopen it and work out how much redesigning would be needed to fix it.
