### ISSUE TITLE
[Question] Is there a way to stop to stop the input clearing when clicked outside?

### ISSUE THREAD

**Issue by llullanqui** [Blazored/Typeahead#198]
After writing in the input, and the selection list appears; if I click outside the input or the list, the text in the input dissapears. 

I have a requirement where the user can choose an item from the list, or just use the text written in the input; and the text clearing does not make it user friendly.

Is there a way to stop the input clearing when clicked outside of it.

**Comment by chrissainty** [comment]
The user must click an item in the list to select it, writing matching text won't trigger a selection.

**Comment by chrissainty** [comment]
There is a new feature which is being released in version 4.6.0 which will allow arbitrary text to be added and selected. I think might resolve your issue.
