### ISSUE TITLE
[Bug] Selecting an item with the mouse doesn't work consistently

### ISSUE THREAD

**Issue by kvroeden** [Blazored/Typeahead#199]
In a Blazor Service side project, with a standalone typeahead, with multiple select (using @value-binds to an IList<Item>) where EnableDropDown=true and ShowDropdownOnFocus =true it is not possible to select via the mouse pointer.

Tabbing into the component will show the dropdown, clicking an item with the mouse will not select it but close the dropdown.
I expect the item to be selected

Another one: If you click with the mouse on the down arrow (right hand side of input) the dropdown opens and you can select with a mouse click as expected. The dropdown stays open but clicking another item will close it (instead of selecting it, which is what I expect).

I want to be able to tab into the component, have the dropdown open and then select multiple items, not sure if the dropdown should stay open because that's not the case when you use the keyboard to select

Thanks

**Comment by merill** [comment]
Dropdown with mouse click not working appears to be a bug in 4.5.1. I reverted to 4.5.0 and mouse click on dropdown is working as expected.

Could this be related to https://github.com/Blazored/Typeahead/commit/590589a01f716a418ee2b952816e1d738ce90ef1
@HAL-NINE-THOUSAND

**Comment by HAL-NINE-THOUSAND** [comment]
Hey guys,

Yeah it looks like I missed removing a reset call on the MultiSelect blur. 

@chrissainty I've put a PR in for the fix and a potential fix for choosing multiple options without the list closing.

**Comment by kvroeden** [comment]
Thanks for the PR and your swift reply, much appreciated. 

Multiple select now works. The only awkward thing is that when you select an item (or many items) you have to click outside the control to actually add then to the selection (closing the dropdown via the arrow button on the right doesn't select, just closes). Maybe when you select with mouse also add to the selected list?

**Comment by chrissainty** [comment]
This is now resovled by #201
