### ISSUE TITLE
[Bug] Current value is not restored after losing focus

### ISSUE THREAD

**Issue by pkuo** [Blazored/Typeahead#200]
The current value is not restored after losing focus. Gives the impression the selected value was cleared.

**To Reproduce**
1, [https://blazored.github.io/Typeahead/](url)
2. Click on input for "Blazored Typeahead - Standalone"
3. Click outside.

**Expected behavior**
Expecting current value shown. Same as pressing Esc on the keyboard.

**Screenshots**
![blazor typeahead](https://user-images.githubusercontent.com/4933969/106041218-84484380-60a9-11eb-8afd-125b2f1d4e54.PNG)

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly

**Comment by pkuo** [comment]
Downgraded to version 4.5.0. Working as expected.

Bug is in version 4.5.1

**Comment by chrissainty** [comment]
Thanks for spotting this @pkuo. This looks like the result of a change we made around input focus. 

@HAL-NINE-THOUSAND - This looks related to the focus changes, when you click on the Typeahead and then click off, the input isn't being hidden and the selected template shown. Any ideas?

**Comment by HAL-NINE-THOUSAND** [comment]
Hi Chris,

I've added this to the PR https://github.com/Blazored/Typeahead/pull/201/commits 

I'd like your thoughts on the multi-select bit, it can be removed if necessary

**Comment by timbze** [comment]
@HAL-NINE-THOUSAND maybe you have addressed this too, but seems it might be related to the OP

When a name is selected, the Focus button does nothing
![2021-02-09 08-59-45 mp4](https://user-images.githubusercontent.com/35117769/107385616-ab930d80-6ab8-11eb-8805-b15389f08d48.gif)

**Comment by HAL-NINE-THOUSAND** [comment]
Thanks @timbze - there's a fix in the PR

**Comment by timbze** [comment]
@HAL-NINE-THOUSAND did you test it? Pulling that branch does not seem to fix it for me...

**Comment by HAL-NINE-THOUSAND** [comment]
@timbze - seems to for me, are you trying something different than this? 

![rjgUxPgMYR](https://user-images.githubusercontent.com/2001016/107542238-e338ad00-6bbf-11eb-9dd4-2b858e69cac4.gif)

**Comment by timbze** [comment]
Ok it actually works now when I do it with button.

I was trying to do it through a web shortcut which does not go through `EventCallback` and so no refresh is called. If I manually call `await InvokeAsync(StateHasChanged)` after `Focus()` then it clears the input but drop-down does not open.

I have `ShowDropDownOnFocus="true"` so when the Typeahead still has focus (i.e. after selecting name), clicking the button does nothing.

If you want to address these things or not is up to you. I probably would use them if it worked for me, but otherwise I will just do something else for now.

**Comment by HAL-NINE-THOUSAND** [comment]
@timbze I'm not sure how you're accessing the component. If you can provide a simple razor page that demos the issue I'll take a look.

**Comment by chrissainty** [comment]
Looking at the thread, I think everything here has been resolved. If there are any outstanding issues can they please be raised as a new issue.
