### ISSUE TITLE
Help ValuesChanged Consultancy

### ISSUE THREAD

**Issue by theafricaninternetgroup** [Blazored/Typeahead#202]
Anyone this Respository who can assist me for the subscribing to ValuesChanged at a fee ,I have checked the so examples given about the same topic I continue getting the null reference and I am now getting frustrated

Many thanks
Dennis

**Comment by chrissainty** [comment]
Hi @theafricaninternetgroup, I would suggest adding the code you're struggling with and then people can give you some advice about what the issue might be.

**Comment by chrissainty** [comment]
Closing due to lack of communication.
