### ISSUE TITLE
List provides scrollbar but doesn't allow scrolling beyond the results showing

### ISSUE THREAD

**Issue by dbowser** [Blazored/Typeahead#206]
**Describe the bug**
When I enter a filter value, the SearchMethod  returns 60 results. Only 10 show as expected. A scroll bar appears on the right as expected. However, I am not able to scroll to the other 50 results. It acts as if only 10 results were returned, although it should not show a scroll bar if that really was the case.

**To Reproduce**
1. Have SearchMethod return significantly more than 10 results.
2. Enter a filter value to trigger SearchMethod.
3. Note the list of 10(default) results.
4. Note the scroll bar on the right side of the list.
5. Try to scroll beyond the list of ten using the keyboard or mouse. 

**Expected behavior**
The list should contain all the results, only show 10(default) at a time, should allow scrolling using the mouse on the scroll bar or by using the arrow keys to scroll up or down through the items or to page through the list 10 at a time using the pageup or pagedown keys.

**Hosting Model (is this issue happening with a certain hosting model?):**
  - Blazor WebAssembly

**Comment by chrissainty** [comment]
Thanks for reporting this @dbowser. I'll take a look when I get a chance. I don't suppose you could attach a screenshot of the issue in the meantime?

**Comment by dbowser** [comment]
OK sure. Here is a redacted snip...
![Capture](https://user-images.githubusercontent.com/3384531/110710513-fee9a000-81cb-11eb-941b-62bc3dcb259e.JPG)

**Comment by chrissainty** [comment]
@dbowser I've just been looking at your issue. I've re-read your opening comment and I've realised there might be a misunderstanding on functionality. The number of results shown in the list is literally the number of results it will display period. This isn't a number per page or anything like that. 

If you want more than 10 results to appear you must up that number. The typeahead filters the results using the characters typed to a point where there is an acceptable number of options for the user to select from. Have 10's or more results isn't a good user experience hence we default the number shown to 10--with the option for individuals to up that number if they choose.

**Comment by dbowser** [comment]
Ah OK. Thank you for explaining that @chrissainty! 
Yes, I tried increasing that number and it provided the experience I was looking for. 
I should have just tried it before but was confused by the description so didn't even try. :) 
Thank you for explaining it to me and thank you for creating this and so many great Blazor components!

**Comment by dbowser** [comment]
Now that I understand the meaning of the 'MaximumSuggestions' parameter it works as I was expecting.
