### ISSUE TITLE
[Bug] Item does not get selected on click with multi select 

### ISSUE THREAD

**Issue by matijs-toonen** [Blazored/Typeahead#209]
**Describe the bug**
Clicking a item in a multi select search will not select this item,
but instead close the dropdown menu.

Only applies to `clicking`, as using `enter` will select the item

**To Reproduce**
1. Search for a item
2. Click the item using the mouse
3. Dropdown will dissapear 
4. The item is not selected

**Expected behavior**
The item gets selected the when clicking the item,
this would be the same as using the `enter` key.

**Screenshots**

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Additional context**
Typeahead version: 4.5.1
.NET version: 5.0.3

**Comment by chrissainty** [comment]
This was fixed as part of #201. There is one other outstanding issue to be fixed and then this will be released.
