### ISSUE TITLE
Event onchange on result template

### ISSUE THREAD

**Issue by aelmen** [Blazored/Typeahead#21]
Since i am a newbee to blazor there might be an easy solution for my question.

Server Side Blazor

I have a main page with a child component that has a typeahead component, three levels, main -> component -> typeahead. How do I bubble up the event from typeahead to the main page?
I've managed to get it to the degree that the event bubbles up to the main page, but then the typeahead component disappears. So I'm probably doing something wrong. Can you put an event callback on the template for the result on change? Or is it a completely wrong implementation?

**Comment by chrissainty** [comment]
I prefer not to add an `EventCallback` as I think it’s best to let the consuming developer decide if they want to call `StateHasChanged` rather than forcing it on them. 

Could you provide some example code of what you’re attempting?

**Comment by aelmen** [comment]
Hi!

Sure. I bet this is an easy task, I just need helt to figured it out.


index.razor

`@page "/"
<ProjektComponent ShowSelectedDetails="true" SelectedProjekt="@SelectedProjekt">
</ProjektComponent>
@if (Equals(SelectedProjekt, null).Equals(false))
{
    <div class="jumbotron">
        <p>@SelectedProjekt.DisplayName</p>
    </div>
}
@code{
    /// <summary>
    /// Here I need an event for ui refresh when selectedprojekt has changed.
    /// </summary>
    Data.Projekt SelectedProjekt { get; set; }
}
`
ProjektComponent.razor
`
@inject Data.Services.ProjektService ProjektService
<BlazoredTypeahead SearchMethod="@Find" MinimumLength="3" Placeholder="Sök" @bind-Value="SelectedProjekt">
    <SelectedTemplate>
        @context.Kund.Name - @context.DisplayName
    </SelectedTemplate>
    <ResultTemplate>
        @context.Kund.Name - @context.DisplayName
    </ResultTemplate>
</BlazoredTypeahead>
@if (Equals(SelectedProjekt, null).Equals(false))
{
    if (ShowSelectedDetails)
    {
        <div>@SelectedProjekt.Kund.Name</div>
        <div>@SelectedProjekt.Kund.Notis</div>
        <div>@SelectedProjekt.DisplayName</div>
    }
}
@code
{
    [Parameter]
    protected Data.Projekt SelectedProjekt { get; set; }
    /// <summary>
    /// 
    /// </summary>
    [Parameter]
    public bool ShowSelectedDetails { get; set; }
    /// <summary>
    ///
    /// </summary>
    /// <param name="searchText"></param>
    /// <returns></returns>
    private Task<List<Data.Projekt>> Find(string searchText)
    {
        return ProjektService.Find(searchText);
    }
}
`

**Comment by chrissainty** [comment]
Ok I think this should work or at least get you most of the way there. 

In your `ProjektComponent` you need to do something like this:

```html
private Data.Projekt _selectedProject;
[Parameter] protected Data.Projekt SelectedProjekt
{
    get => _selectedProject;
    set
    {
        _selectedProject = value;
        OnProjectChanged?.Invoke(_selectedProject);
    }
}
[Parameter] Func<Data.Projekt> OnProjectChanged { get; set; }
```

Then in your parent component do this:

```html
<ProjektComponent OnProjectChanged="HandleProjectChanged" />

@if (Equals(SelectedProjekt, null).Equals(false))
{

    @SelectedProjekt.DisplayName

}

@code{
    /// Here I need an event for ui refresh when selectedprojekt has changed.
    Data.Projekt SelectedProjekt { get; set; }

    private async Task HandleProjectChanged(Data.Projekt selectedProjekt)
    {
        SelectedProjekt = selectedProjekt;
        StateHasChanged();
    }

}
```

Let me know how you get on.

**Comment by aelmen** [comment]
Since the Func<Data.Projekt> did not allow me to pass any args when doing invoke I switched to use an Event Handler.

In Child Component
``` 
   /// <summary>
    /// Private Placeholder
    /// </summary>
    private Data.Projekt _selectedProjekt;
    /// <summary>
    /// Data Binding
    /// </summary>
    [Parameter]
    protected Data.Projekt SelectedProjekt
    {
        get => _selectedProjekt;
        set
        {
            _selectedProjekt = value;
            OnProjectChanged?.Invoke(this, _selectedProjekt);
        }
    }
    /// <summary>
    /// Event Handler
    /// </summary>
    [Parameter] EventHandler<Data.Projekt> OnProjectChanged { get; set; }
```

In Parent Component
``` 
<ProjektComponent ShowSelectedDetails="true" OnProjectChanged="HandleProjectChanged" >
</ProjektComponent>

@if (Equals(SelectedProjekt, null).Equals(false))
{
    <div class="jumbotron">
        <p>@SelectedProjekt.DisplayName</p>
    </div>
}
@code{
    /// <summary>
    /// 
    /// </summary>
    protected Data.Projekt SelectedProjekt { get; set; }
    /// <summary>
    /// Event Handler
    /// </summary>
    /// <param name="sender"></param>
    /// <param name="projekt"></param>
    void HandleProjectChanged(object sender, Data.Projekt projekt)
    {
        SelectedProjekt = projekt;
        StateHasChanged();
    }
}

```

This seem work like a charm. I have no idéa of if this is a good implementation or not. Any suggestions?

I belive you can close this issue now since there is no need for an event on the result template.

**Comment by chrissainty** [comment]
Glad to hear you got it sorted, I’m not sure why you had an issue with using `Func<>` though.

**Comment by aelmen** [comment]
Thats was just beacuse the Func<> did not work with invoke(arg).
To get that one working I had to do a Func<in,out>

**Comment by fnils** [comment]
I've been trying to make this work but I can't understan how to change IT. 
I get "No Overload for method Invoke takes one argument" for the following code. OnProjectChanged?.Invoke(_selectedProject);
