### ISSUE TITLE
Result List hidden within Telerik Modal[Bug]

### ISSUE THREAD

**Issue by cmaluft** [Blazored/Typeahead#214]
**Describe the bug**
I have a telerik window with modal, your typeahead is a component in the modal. When text is typed and a result returned the dropdown list is hidden in the modal.(see image). 
![typeahead_hidden](https://user-images.githubusercontent.com/60627062/110947674-1462e500-8306-11eb-90ca-0796b7034b05.png)

**Expected behavior**
I expected the result list to be in front of the modal and expand down so all results can be viewed and the modal didn't need to use vertical scrollbars.

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Additional context**
component code: UserPicker.razor
```
<div class="container">
    <div class="row">
        <div class="col-8">
            <Blazored.Typeahead.BlazoredTypeahead SearchMethod="UserPickerSearch"
                                                  
                                                  TValue="ImportUserSearchResult"
                                                  TItem="ImportUserSearchResult"
                                                  Value="SelectedUser"
                                                  ValueChanged="UserSelected"
                                                  ValueExpression="@(()=>SelectedUser)"
                                                  MinimumLength="3"
                                                  PlaceHolder="Search name or email...">
                <SelectedTemplate>
                    @context.FullName
                </SelectedTemplate>
                <ResultTemplate>
                    <div class="pb-2">
                        <b>@context.FullName</b><span style="float:right"> @context.FunctionalGroup</span>
                    </div>
                    <div class="pb-2" style="color:lightgrey; font-size:smaller; border-bottom:solid">
                        @context.Email <span>| @context.Title</span>
                    </div>

                </ResultTemplate>
            </Blazored.Typeahead.BlazoredTypeahead>
        </div>       
    </div>
</div>
```
-----------------------------
window code:
```
<TelerikWindow @bind-Visible="@IsVisible" Modal="true" Size="WindowSize.Medium" Centered="true" Width="">
    <WindowTitle>
        <div class="main-heading">
            <strong>Create Subject</strong>
        </div>
    </WindowTitle>
    <WindowContent>
        <div class="notification-parent">
            <TelerikNotification @ref="NotificationComponent"
                                 Class="subject-notification"
                                 HorizontalPosition="@NotificationHorizontalPosition.Center"
                                 VerticalPosition="@NotificationVerticalPosition.Top"></TelerikNotification>
        </div>
        <div class="main-heading">
            <h6>To get started, please add a subject to the survey by entering their name or email.</h6>
        </div> 
        <div class="components">
            
**_//This is your typeahead component:_** 
> <UserPicker ImportProjectId="@ImportProjectId" OnAddPersonClicked="CreateNewUser" OnExistingUserSelected="ExistingUserSelected"></UserPicker>

        </div>
    </WindowContent>
    <WindowActions>
        <WindowAction Name="Close" OnClick="() => SetVisible(false)"></WindowAction>
    </WindowActions>
</TelerikWindow>
```

**Comment by chrissainty** [comment]
@cmaluft Apologies for taking a while to get to this one. Could you try something for me. Could you up the z-index on the `.blazored-typeahead__results` CSS class. By default it is 10, but could you up it and see if the results list starts to show correctly after a certain number? You can do this using the browser dev tools while your app is running. 

If you find a number which allows the results list to show correctly I can update the components CSS to default to that value.

**Comment by cmaluft** [comment]
There wasn't any z-index that worked unfortunately. I did changed the position to fixed and width: 58%. Its probably not the solution but I did get this result. Not sure of all the ramifications 
![typeahead](https://user-images.githubusercontent.com/60627062/112724312-bc6cd680-8ee0-11eb-8947-93af193e23a7.png)

**Comment by chrissainty** [comment]
Umm.. I'm not sure what Telerik are doing with their modal which would stop the z-index making a difference. 

I think I'm going to suggest you use some custom CSS, like what you've tried in your comment. I don't think there is anything I'd want to change in this library at the moment. Sorry I couldn't help on this one.
