### ISSUE TITLE
Custom Icon

### ISSUE THREAD

**Issue by raphadesa** [Blazored/Typeahead#220]
Hello Team,

This component is just awesome !

I have a suggestion :

Could you add a custom clickable  icon (Font-Awesome or SVG) of a magnifying glass to the right corner of the component ?

Thank you very much !

Raphaël Desalbres

**Comment by chrissainty** [comment]
Hi @raphadesa, I'm glad you like the component. 

What would you expect this new button to do when clicked? We wouldn't add a new element like this without a specific use-case.

**Comment by raphadesa** [comment]
Hi Chris, could you please remove this post, as I got mistaken ! Sorry about that !

________________________________
De : Chris Sainty ***@***.***>
Envoyé : Saturday, April 17, 2021 9:18:55 AM
À : Blazored/Typeahead ***@***.***>
Cc : Raphaël Desalbres ***@***.***>; Mention ***@***.***>
Objet : Re: [Blazored/Typeahead] Custom Icon (#220)


Hi @raphadesa<https://github.com/raphadesa>, I'm glad you like the component.

What would you expect this new button to do when clicked? We wouldn't add a new element like this without a specific use-case.
