### ISSUE TITLE
[Question] MultiSelect - Typehead Dropdown

### ISSUE THREAD

**Issue by parente89** [Blazored/Typeahead#228]
Good evening, congratulations for the excellent work done. I was wondering if it is possible to use the component to make a MultiSelect.
If it is possible, can you tell me how I can do it?
Thanks so much!

**Comment by chrissainty** [comment]
Yes. There is an example of how to do this in the samples folder.

https://github.com/Blazored/Typeahead/blob/9d5f03386ca2569e94c18a60fc2dd99aae55576d/samples/BlazorWebAssembly/Pages/Index.razor#L152
