### ISSUE TITLE
No inputs were found in config file 

### ISSUE THREAD

**Issue by fnils** [Blazored/Typeahead#23]
After upgrading to asp.net core Preview-8 and TypeAHead 3.13 I get the following error  (same with 3.12).
Build:No inputs were found in config file C:/Users/username/.nuget/packages/blazored.typeahead/3.1.3/contentFiles/any/netstandard2.0/tsconfig.json'. 
Specified 'include' paths were '["**/*"]' and 'exclude' paths were '["wwwroot"].

**Comment by chrissainty** [comment]
Thanks @fnils. There seems to be problems with the new razor class library and typescript. I'm trying to get to the bottom of it.

**Comment by chrissainty** [comment]
@fnils If you update to the latest version this should be resolved.

**Comment by fnils** [comment]
@chrissainty Ok, great! I will try it as soon as I get the chans. Thank you!

**Comment by fnils** [comment]
It works. I had to update the css and js code manually after updating it through nuget package manager in Visual Studio.

**Comment by chrissainty** [comment]
When you update, do you mean you had to add the css and script tag manually?

**Comment by fnils** [comment]
I copied the code in the files here on github (src/Blazored.Typeahead/wwwroot) to the files I hade from a previous installation.

**Comment by chrissainty** [comment]
Ah ok. That should work automatically now but there are some issues with the new Razor Class Library and nothing is really working properly right now. Copying the CSS and JS manually into your project seems the only way to get stuff working.
