### ISSUE TITLE
[Bug] Could not find blazoredTypeahead.addKeyDownEventListener

### ISSUE THREAD

**Issue by rlebowitz** [Blazored/Typeahead#231]
This same bug was reported back in Mary 2021 in Bug #188; I'm seeing the same problem.  Reloading the page appears to resolve the issue, but of course, this isn't really a good solution.  I have a couple of other component libraries that I load as well, none of them appear to have similar issues.

The error also states that blazoredTypeahead is not defined, suggesting that all the js methods that are invoked by the component are unavailable.

Like the previous bug report, I reference the javascript in index.html (this is a hosted wasm application) BEFORE the reference for the blazor.js 

I'm using .NET 5.0.6 - I'm not certain whether this would have any effect.

**Comment by rlebowitz** [comment]
Ok, I did discover that the order in which the various 3rd party interop javascripts are loaded is critical; I placed blazored-typeahead.js as the first of three external scripts (the other two are gridblazor.js and tinymce-blazor.js), and all of the ahead of blazor.webassembly.js.  

Oh, and I load AuthenticationService.js from the Microsoft Authentication library before I load blazored-typeahead.js

I hope this information may help someone else.

**Comment by chrissainty** [comment]
Thanks for posting your solution @rlebowitz. This often seems to come down to a cached file somewhere, browser sometimes really hold on to these files. We use this component at my work and we load the JS in a totally different order to what you've described and we've never had an issue. It's a weird one.

I'm planning on rewriting the component when I have time and when I do I'm going to probably move over to JavaScript modules so the burden won't be on the developer to include a script file at all. The framework can just load the necessary JavaScript when it's needed.

Anyway as you've reached a solution I'm going to close this issue. Thanks again for sharing your solution.

**Comment by rlebowitz** [comment]
FYI:

 

When I started work this morning, the issue reappeared.  I tried clearing my cache again, and it seems to work fine now; I have no idea why.

**Comment by lthoa** [comment]
Waiting for a second before call **AddKeyDownEventListener** will be fix the problem:

protected override async Task OnAfterRenderAsync(bool firstRender)
  {
      if ((firstRender && !Disabled) || (!_eventsHookedUp && !Disabled))
      {
          await InvokeAsync(async () =>
          {
              await Task.Delay(1000);
              await Interop.AddKeyDownEventListener(JSRuntime, _searchInput);
              _eventsHookedUp = true;
          });                
      }
  }

**Comment by jmouradelo99** [comment]
Change 4.40 version
