### ISSUE TITLE
Is there a way to manually trigger search. I am thinking of 

### ISSUE THREAD

**Issue by ashfaquddin** [Blazored/Typeahead#239]
The use case is to trigger search using a paging component placed on Footer

**Comment by chrissainty** [comment]
I don't see this personally. The idea of the typeahead is to allow users to type in character to limit their results. If they are seeing so many results that paging is required then I think a typeahead is not the right option for that scenario.

**Comment by syedfahimabrar** [comment]
I would be very happy as @ashfaquddin  if there was a feature. My intention is also the same as his.

**Comment by chrissainty** [comment]
Hi @syedfahimabrar, please see my last comment. I don't see this as something that makes sense for the typeahead.
