### ISSUE TITLE
Could not load type 'Microsoft.AspNetCore.Components.ElementRef' from assembly 'Microsoft.AspNetCore.Components

### ISSUE THREAD

**Issue by dolare1** [Blazored/Typeahead#24]
I recently upgraded from ASP.NET Core 3.0 Preview 7 to Preview 8 and noticing below error:

Could not load type 'Microsoft.AspNetCore.Components.ElementRef' from assembly 'Microsoft.AspNetCore.Components

I am suspecting it is due to a breaking change as mentioned in this link: https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8/

"Rename ElementRef to ElementReference."

Any pointers?

**Comment by dolare1** [comment]
Looks like I need to reinstall the package? Is that correct?

**Comment by chrissainty** [comment]
Hi @dolare1, you need to upgrade to the latest version of the package. Once you've done that, I would suggest doing a full clean and rebuild of your solution and emptying your browser cache.

There are currently a few issues with the new Razor Class Library project so you may find issues with the `blazored-typeahead.js` file not being included. If you hit this issue then the only option right now is to copy the JS file from this repo into your projects `wwwroot` folder and reference it from there. 

Hope that all makes sense.

**Comment by dolare1** [comment]
Thanks, that worked. I just had to reinstall the package.
