### ISSUE TITLE
SearchMethod should be IEnumerable

### ISSUE THREAD

**Issue by alexandrereyes** [Blazored/Typeahead#25]
Is there any reason that SearchMethod needs to be List<T> ? IEnumerable<T> is the best choice to collection parameters.

**Comment by chrissainty** [comment]
Hi Alexandre, the simple answer is no. `SearchMethod` was typed as a List initially while prototyping and just hasn't been changed. I agree that an IEnumerable would be a better design choice. I'll look to swap it over at some point in the future.

**Comment by alexandrereyes** [comment]
@chrissainty what's the impact since `List<T>` is `IEnumerable<T>`? I think there is no problem in change to `IEnumerable<T>`

**Comment by chrissainty** [comment]
@AlanCS I never said there was a problem, it's time. I'm very busy and I'll make the change when I can. But please feel free to make the change and create a PR if you would like to see it deal with quicker!
