### ISSUE TITLE
[Question] Alter position of loading indicator?

### ISSUE THREAD

**Issue by philvessey** [Blazored/Typeahead#251]
Hi - is it possible to alter the position of the loading indicator - its not centred vertically and id like to change that if possible?

<img width="65" alt="image" src="https://user-images.githubusercontent.com/814882/139210289-7933e12d-7f3c-4734-91a6-e4ac6daa22e7.png">

**Comment by NessfertIndia** [comment]
@philvessey  What all CSS adjustments you  made ? Can you please share that as well?

**Comment by philvessey** [comment]
@NessfertIndia Sure will post them a bit later on today.

**Comment by philvessey** [comment]
@NessfertIndia These were the css elements I did some overrides on:

`
.blazored-typeahead {
  border: none !important;
  border-radius: none !important;
  box-shadow: rgba(0, 0, 0, 0.16) 0px 0px 4px;
}

.blazored-typeahead__loader {
  background-color: black !important;
  height: 20px !important;
  position: absolute;
  right: 6px;
  top: 6px;
  width: 20px !important;
}
`

I used the !important tags to override
