### ISSUE TITLE
onfocusout should hide the suggestions

### ISSUE THREAD

**Issue by vertonghenb** [Blazored/Typeahead#26]
Currently the suggestions are not hidden when the input loses focus. This won't be an easy fix if you only use C# though. Since the `onfocusout` event isn't fully supported in Blazor yet.

**Comment by chrissainty** [comment]
Agreed, this is why the issue exists in the first place. I was trying to keep to pure C# but I ended up having to use focus anyway. Interop is the only answer for this one I think.
