### ISSUE TITLE
After showing suggestions make the first item selectable by using tab

### ISSUE THREAD

**Issue by vertonghenb** [Blazored/Typeahead#27]
1. Search Item
2. Get suggestions
3. Use tab to select the first one.

**Comment by chrissainty** [comment]
Based on what other typeahead controls do, it might be good to be able to select the first item by either tab OR the down arrow. That way users can type and then just keep pressing down rather than having to type > tab > down arrow. I think both should be an option though.

**Comment by vertonghenb** [comment]
I tried the arrow keys but failed, the tab can currently be done though. The arrow buttons get annoying when a scrollbar is in place since you also scroll using the arrow keys and there is no way to stop this from happening in Blazor at the moment.

**Comment by egrabitt** [comment]
Thank you Chris and Benjamin for your awesome typeahead control! I just found it and I was able to replace a jQuery based hack in my Server-side Blazor in no time. Much cleaner. However the Tab-behavior bothers me as it forces me to use the mouse. 

You say "it might be good to be able to select the first item by either tab OR the down arrow." I second that! 

Specifically, I'd like the control to behave like this:  If you press Tab after typing something, the first suggestion is put into the typeahead input field **and the form's next input is focused**. So Tab behaves just like in a regular form with text input fields. 
One "safety option" could be that a suggestion is only used if there is only one in the list.
Do you think this is possible?

Thanks again, Ernie

**Comment by vertonghenb** [comment]
@egrabitt check the gif at #31 I think it behaves as you'd like.

**Comment by egrabitt** [comment]
thanks for your reply, but no, it doesn't. Pressing tab should move the focus to the form's next input element, putting the topmost typeahead suggestion into the now previous element.
