### ISSUE TITLE
Endless onfocus loop

### ISSUE THREAD

**Issue by vertonghenb** [Blazored/Typeahead#29]
There is an endless loop occuring in the component.
To reproduce:
1. Set a breakpoint in the setter of the `_searchText` 
2. Optionally set the default `Debounce` value to `5000000` (so we know it's not coming from here.
=> endless onfocus loop

To fix this issue:
- change onfocus to onclick in the `input` of the control.

**Comment by chrissainty** [comment]
Good spot, we'd seen this at work using the control but hadn't had a chance to narrow it down. Great catch!
