### ISSUE TITLE
Consider using Invoke

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [Blazored/Typeahead#3]
https://github.com/Blazored/Typeahead/blob/62986b4cdc48af42137a834dcbe67a272e5de660/src/Blazored.Typeahead/BlazoredTypeahead.razor.cs#L72

In the Search method you are executing on the context of a timer, and might want to use 

Invoke (StateHasChanged);

To protect against synchronisation context issues.

**Comment by chrissainty** [comment]
Thanks for this, I've merged a fix.
