### ISSUE TITLE
merge my fork in

### ISSUE THREAD

**Issue by pwelter34** [Blazored/Typeahead#34]
Its been suggested that I merge my fork back into this project.  However the code has drifted a lot.  Do we still want me to merge my source in?  

Issues/Differences

1.  I made large changes to the html and css structure.  We'd need to pick the best UI.
2.  I removed the need for the separator form input control.  
3.  Added multi-select support
4.  Added keyboard selection support
5.  Added support for binding to a diff value then what the search result is

thoughts?

Demo: [LoreSoft Blazor Controls](http://blazor.loresoft.com/typeahead/index)
Repo: [LoreSoft.Blazor.Controls](https://github.com/loresoft/LoreSoft.Blazor.Controls)

thanks,
~ Paul

**Comment by vertonghenb** [comment]
@pwelter34 Paul, looks good! Maybe we can combine the 2 ? Personally I don't like the second searchbar, but that's rather subjective. The other stuff looks great especially the 2 controls merged into 1.

**Comment by vertonghenb** [comment]
@pwelter34 
Agreed, one good version should be best for the community. 
Therefore I believe it's best to merge in your changes with the following improvements:
- **1 control to search/show the values**, I think it's the way to go and makes the design cleaner, you can check out the [Sync Fusion Control](https://www.syncfusion.com/blazor-components/blazor-multiselect-dropdown), which does this.
- **Support Escape,** you can check out the escape fix I made using the event system and Interop class. 
- **Support Tab**, currently when you tab into the search, you proceed to the next form control. I think it would be better to go to the first option in the list, basically adding a `tabindex=0` should suffice.

**Comment by chrissainty** [comment]
Great discussion. I agree very much with getting your changes merged in @pwelter34. 

I think @vertonghenb comments above make a lot of sense. I also have a suggestion or two but perhaps it would be best to get the PR raised then we can sort things out on there? 

What do you both think?

**Comment by vertonghenb** [comment]
@pwelter34 any update on this? You can reach out to me on Gitter if you need something.

**Comment by pwelter34** [comment]
sorry, was on vacation most of last week.  I'll get a PR open early this week.

**Comment by vertonghenb** [comment]
@pwelter34, how is the PR coming along?
