### ISSUE TITLE
Replicate the Size attribute on the HTML Select element.

### ISSUE THREAD

**Issue by Gareth064** [Blazored/Typeahead#45]
Would it be possible to replicate this feature where instead of it being a drop down, it can be a list box, where you set the size of it. And the search bar filters the list as it currently does?

**Comment by Gareth064** [comment]
After downloading the source code, would adding another parameter which forces the IsShowingSuggestions  to be true at all times?

And I noticed the the size of the results (suggestions list) is done by min and max-height css values, maybe there can be an enum to select sm md lg size?

**Comment by chrissainty** [comment]
Hi @Gareth064, I'm not sure I follow what you're asking for? Do you have an example you could link to?

**Comment by Gareth064** [comment]
When you add the attribute 'size' to a select element, it doesn't render as a drop down anymore, but an always open list with a scrollbar.

![image](https://user-images.githubusercontent.com/22307223/65123269-bf812f80-d9ea-11e9-8427-57c439d5239b.png)

It would be cool if there was a parameter, maybe 2 of them, which would allow your Typeahead dropdown become a Typeahead list. 

The first paramater to make it an always open list
The second parameter to define the size of it.

**Comment by vertonghenb** [comment]
@Gareth064 we're not using a `Select` but a styled div, so adding a `size` attribute won't work. But I'm not sure what you're requesting.
```cs
        <div class="blazored-typeahead__results">
            @foreach (var item in Suggestions)
            {
                <div @key="item" class="blazored-typeahead__result @GetSelectedSuggestionClass(item)" tabindex="0" @onclick="@(_ => SelectResult(item))" @onkeyup="@((e) => HandleKeyUpOnSuggestion(e,item))">
                    @if (ResultTemplate != null)
                    {
                        @ResultTemplate(item)
                    }
                    else
                    {
                        @item.ToString()
                    }
                </div>
            }

            @if (FooterTemplate != null)
            {
                <div class="blazored-typeahead__results-footer">
                    @FooterTemplate
                </div>
            }
        </div>
```

**Comment by Gareth064** [comment]
Sorry, I wasn't very clear with my explanation 😄 Would you be able to replicate the functionality that you would get from using a Select element and its Size attribute? From what I could tell from your code, you have a boolean to control whether the list of suggestions is open\visible, and then the size of it is a CSS property(can't remember off the top of my head which one). So I suppose if the boolean was forced to true always, by a parameter, and you have a enum for a list of sizes (sm md lrg) which translate into the CSS value. Then would that work maybe?

This is my first venture into GitHub and the open source scene, so apologies if I am going about this all the wrong way lol.

**Comment by chrissainty** [comment]
Thanks for taking the time to clarify things Gareth. And you're going about things in the right way having this discussion. 😄 

However, I'm going to say this is probably not a change we would make right now. As it stands, a user can get a list of options with a single click with the current implementation. I'm also worried about not making the control do too much. 

@vertonghenb Do you have a different opinion on this?

**Comment by Gareth064** [comment]
@chrissainty No worries.

I will take a fork or clone (I'm an Azure Devops user, GitHub is new to me lol) of this repo after the next major release and see if I can get working what I was suggesting. It will be a fun wee exercise.
