### ISSUE TITLE
Cannot programmatically clear search text

### ISSUE THREAD

**Issue by Jerrgree** [Blazored/Typeahead#51]
I am currently running using Typeahead 3.1.8

After certain actions, I am attempting to clear the Typeahead search bar so that the user can perform a new search. I do this by setting the bound value to string.Empty

It appears that the value has been cleared in the UI, however, as soon as I focus on the text box the previously cleared value re-appears.

![typeaheadExample](https://user-images.githubusercontent.com/10146723/66691574-1fbb6800-ec5d-11e9-8740-add65c815030.gif)

**Comment by chrissainty** [comment]
Thanks for reporting this @Jerrgree. I think this is a bug we need to sort out. We're currently working on a new version of the control so I'll get this fixed in that branch so it's in the next major release.

**Comment by chrissainty** [comment]
Resolved by #46

**Comment by artuise** [comment]
> I am currently running using Typeahead 3.1.8
> 
> After certain actions, I am attempting to clear the Typeahead search bar so that the user can perform a new search. I do this by setting the bound value to string.Empty
> 
> It appears that the value has been cleared in the UI, however, as soon as I focus on the text box the previously cleared value re-appears.
> 
> ![typeaheadExample](https://user-images.githubusercontent.com/10146723/66691574-1fbb6800-ec5d-11e9-8740-add65c815030.gif)

¿How do you clear text in typeahead?

**Comment by artuise** [comment]
> Resolved by #46

¿How do you clear text in typeahead?

**Comment by Greg7931** [comment]
Hello, same issue for me but it seems issue is not solved by new release.
