### ISSUE TITLE
Add a disabled parameter

### ISSUE THREAD

**Issue by rpskelton2** [Blazored/Typeahead#52]
For use in a business application having a disabled option is a must (or we could create a look-alike control to show instead but ick!)  Please add disabled support!

If Disabled is true:

- Disable input element
- HandleClear and ShowMaximumSuggestions should not be wired or should return before doing any work
- Hover effects over blazored-typeahead__input__icon should be disabled
- placeholder text should not be shown

**Comment by chrissainty** [comment]
Agreed, I'll add this to the list for the next release.
