### ISSUE TITLE
Free text entry - Add item to the list.

### ISSUE THREAD

**Issue by chrissainty** [Blazored/Typeahead#55]
Investigate the ability to add the text entered as a search, as a new value. I'm not sure that makes sense to anyone else, but I know what I mean! 😆 

The example would be if the typeahead was used for selecting a city. If the city exists a user can select it as normal, if it doesn't it can be added.

**Comment by vertonghenb** [comment]
Maybe use the footer as ADD to list? Something like the github labels

**Comment by chrissainty** [comment]
Great mind! I thought about that and hit the same issue as you. 

This feature is fine when dealing with primitives like string or int but complex type aren't going to work as far as I can tell.

**Comment by vertonghenb** [comment]
We could ask for a second function CreateIfNotExists as parameter which is basically a constructor to create T Based on the search value.

**Comment by chrissainty** [comment]
That sounds like a good plan @vertonghenb. It gives the most flexability to the developer and doesn't make things too complex to handle.

**Comment by vertonghenb** [comment]
Note to self:
- Check if we have issues with the `Convert Method` taking this approach

**Comment by Whyskass** [comment]
Hey guys,

Any updates concerning this Free Text Entry issue? 

Thanks anyway for the great job you're doing :)

Best,
L.

**Comment by chrissainty** [comment]
Not yet @Whyskass. We'll get to this ASAP though, I've had a lot of other bits on recently so been a bit short on time.

**Comment by Whyskass** [comment]
Sure no problem, thanks for the answer @chrissainty ;)

**Comment by vertonghenb** [comment]
This is going to be blocked by #66

**Comment by Justincale** [comment]
Hi Guys,

I think, if i have read this correctly, that i may have a solution for very simple entities (in this case a Category has only Id and Name fields). I have a typeahead component that allows the user to search for categories as such:

            <BlazoredTypeahead SearchMethod="SearchCategories" EnableDropDown="true" placeholder="Select Category"
                               @bind-Value="@Component.Category" Context="Category">

                <SelectedTemplate>
                    @{
                        Component.CategoryId = Category.Id;
                    }

                    @Category.Name
                </SelectedTemplate>
                <ResultTemplate>
                    @Category.Name
                </ResultTemplate>
                <NotFoundTemplate>
                    Category not found. <MatButton Icon="create" OnClick="@CreateCategory" Label="Create?"></MatButton>
                </NotFoundTemplate>
            </BlazoredTypeahead>


Take note of the 'NotfoundTemplate' where i have a button to create the category.

That CreateCategory method looks like this:

    private void CreateCategory()
    {
        Component.Category = new ComponentCategoryDto();

        Component.Category.Name = categorySearch;

        StateHasChanged();
    }

Where i simply set the desired name of the entity to a variable named categorySearch. CategorySearch is set in the SearchCategories method:

    private async Task<IEnumerable<ComponentCategoryDto>> SearchCategories(string searchText = null)
    {
        categorySearch = searchText;

I'm not really sure how we would deal with Creating a Category (or any entity) that has multiple required fields but for simple cases this seems to work.

**Comment by vertonghenb** [comment]
@Justincale pretty sweet solution!

**Comment by chrissainty** [comment]
Just doing some housekeeping and it seems like @Justincale solution works without needing any modification our end. Based on that, I'm going to close this issue as there is a workable solution. 

Anyone please feel free to reopen if further discussion is needed.

**Comment by vertonghenb** [comment]
This baby should be documented, Reopening to track in the FAQ

**Comment by fnils** [comment]
If you can choose to "lock" the no results view in open mode. Then you could add textboxes and button  for adding in it.
` <BlazoredTypeahead SearchMethod="SearchItems"
                       @bind-Value="SelectedItem"
                       Placeholder="Area">

        <SelectedTemplate>
            @context.Name 
        </SelectedTemplate>
        <ResultTemplate>
            @context.Name
        </ResultTemplate>
        <NotFoundTemplate>
                    <div class="col">
                        <RadzenTextBox Label="Area" @bind-Value="ItemName" />
                    </div>
                    <div class="col"><RadzenButton Raised="true" Click="@(async () => await Save())">Add area </RadzenButton></div>
        </NotFoundTemplate>
    </BlazoredTypeahead>`

**Comment by chrissainty** [comment]
This is now covered by the feature introduced in PR #215
