### ISSUE TITLE
Add CssClassses from EditContext.FieldCssClass to input

### ISSUE THREAD

**Issue by magahl** [Blazored/Typeahead#58]
Much like InputBase in AspNetCore ([here](https://github.com/aspnet/AspNetCore/blob/8c02467b4a218df3b1b0a69bceb50f5b64f482b1/src/Components/Web/src/Forms/InputBase.cs#L146)) the status classes from the EditContext should be added to the input. This is needed so that we can style the input itself when it is valid, invalid and modified.

**Comment by chrissainty** [comment]
Agreed. I've added a comment to your PR with a suggestion for a slight change.
