### ISSUE TITLE
Clicking on footer template closes suggestion list

### ISSUE THREAD

**Issue by natsuo** [Blazored/Typeahead#66]
Clicking on the footer template, or any of the elements inside the footer template causes the component to close the suggestion list.

The footer template can be used in a variety of ways, including:
* Showing suggestion/item count.
* Showing a label with a description or help.
* Showing a link/logo to the service providing the suggestions (like weather service provider).

Clicking outside the list entirely should obviously close the suggestions list.

**Comment by chrissainty** [comment]
Thanks for reporting this @natsuo. Definitely something we need to get fixed!

**Comment by chrissainty** [comment]
I think we need to establish the use cases for the footer/header templates. I can add a link to the footer template and I can click on the link without issue. Yes, the suggestion list then closes but I'm not sure why it should stay open.

@natsuo Could you clarify the type of behaviour you're after and maybe some context?

**Comment by natsuo** [comment]
This example shows header and footer templates. Footer has item count. Header has button to create a new product and to toggle if disabled items should be shown in the list or not.

![expected](https://user-images.githubusercontent.com/1655659/67760117-024e1280-fa41-11e9-9995-338c17f84c2a.gif)

**Comment by vertonghenb** [comment]
**Maybe** this is something we can easily fix with the new Blazor version (3.1 p2+)
`Stop event propagation in Blazor apps` 
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-1-preview-2/

**Comment by chrissainty** [comment]
You might be right @vertonghenb. Do you want to have a go at this one? If not I'll code it up when I get a chance.

**Comment by chrissainty** [comment]
@vertonghenb I've tried using the new prevent default directive but no joy at all. It no effect. I put a prevent default on every event and still nothing was blocked.

**Comment by vertonghenb** [comment]
@chrissainty Hehe, I tried the exact same thing but no luck, well it worked in the standalone example. But the validation while using it in a form messes things up.

**Comment by chrissainty** [comment]
I'm doing some housekeeping. Looking back at this issue now it seems like we need to take some more aggressive steps to keep the suggestion list open after clicking on a header or footer link. 

Personally, I'm not sure it's something we should look to do right now. As I mentioned before I think this would involve a lot more JS and I'm not sure of the demand for this feature. Based on all this I'm going to close this issue for now. But please reopen if anyone feels this needs more discussion/attention.
