### ISSUE TITLE
Add ability to set focus to the input box

### ISSUE THREAD

**Issue by Joe-LaRue** [Blazored/Typeahead#69]
A use case for this is as follows - when showing a modal with a typeahead component, it would be nice to set the focus to the input box so the user can just start typing.  The same could apply when navigating to a page with a typeahead component.

**Comment by Joe-LaRue** [comment]
It looks like the way to do this is to instantiate an instance of the typeahead, reference it in the markup declaration via the @ref attribute, and then call a method on the component when needed.

example:
![typeAhead1](https://user-images.githubusercontent.com/51251572/67895479-f3df2400-fb30-11e9-9061-de5aabc77bbe.PNG)
![typeAhead2](https://user-images.githubusercontent.com/51251572/67895481-f5a8e780-fb30-11e9-9e74-d799612eced4.PNG)

**Comment by vertonghenb** [comment]
You could do this with some JS and using the .css class of the control.
However @chrissainty  and myself have been thinking to create a Blazored.Essentials package so you could express this easier for example:

```html
<BlazoredTypeahead SearchMethod="GetPeopleLocal"
                   @ref="myTypeahead"
                   @bind-Value="SelectedPerson"
                   ShowDropDownOnFocus="true"
                   placeholder="Search by first name...">
    <SelectedTemplate Context="person">
        @person.Firstname
    </SelectedTemplate>
    <ResultTemplate Context="person">
        @person.Firstname @person.Lastname
    </ResultTemplate>
</BlazoredTypeahead>
```
```cs
@code {
    ElementReference myTypeahead;
    protected override void OnInitialized()
    {
         myTypeahead.Focus();
    }
}
```

**Comment by Joe-LaRue** [comment]
I'd be interested in pitching in if you want the help :)

**Comment by chrissainty** [comment]
@vertonghenb Yes - we should make a move on that project. Blazored.Essentials seems like a good name. I'll get the repo created.

@Joe-LaRue The more the merrier, I'll get the repo setup then we can get some issues going

**Comment by chrissainty** [comment]
I am I right in thinking this issue can be closed now @Joe-LaRue ?

**Comment by Joe-LaRue** [comment]
Yea - it sounds like the plan is to handle it via Blazored.Essentials.
