### ISSUE TITLE
When there is a selected item and a search is performed but no result selected, leave search mode on focus out

### ISSUE THREAD

**Issue by chrissainty** [Blazored/Typeahead#7]
Currently when searching, if no result is selected but there is already a selected item from a previous search Losing focus on the search input leaves an empty field, this should switch back to the `SelectedTemplate`.

**Comment by vertonghenb** [comment]
@chrissainty  I guess we need to re-evaluate this one?

**Comment by chrissainty** [comment]
Agreed, this is probably a bit of a relic now, considering the new changes. 

I'd be happy to close if you are?
