### ISSUE TITLE
Show suggestions on ArrowDown/Enter when input has focus and suggestions arent already showing

### ISSUE THREAD

**Issue by magahl** [Blazored/Typeahead#71]
If the input has focus and a user push `ArrowDown` or `Enter` it should `ShowMaximumSuggestions` (much like the handler on the dropddown arrow icon).

This is very convenient when tabbing through a form and you wanna open the suggestions fast (and you dont wanna show all options on focus).

**Comment by chrissainty** [comment]
@magahl Thanks for this suggestion. I agree it would be a benefit but I'm not sure about your approach. I would rather only enable this option if the EnableDropDown parameter has been set to true. Showing suggestions outside of this is a bit of a blur of function for me. What are your thoughts?

**Comment by magahl** [comment]
That was my first implementation actually. I didn't find a reason to limit the functionality, but if you think its better  then it problably is. I can update the PR with this.

**Comment by chrissainty** [comment]
Maybe I'm overthinking it. I was thinking of how we use the control at work, where we use it as a typeahead only there can be 1000's of results allowing the down arrow function would be pretty worthless. Where as if the drop down function has been enabled then potentially there are only a limited amount of options.

**Comment by magahl** [comment]
Yeah, indeed that would be pretty bad.
