### ISSUE TITLE
Add support for Enter, Tab keys to finish selection

### ISSUE THREAD

**Issue by rgamage** [Blazored/Typeahead#76]
Once you've narrowed down the list to only one option, user should be able to hit Enter or Tab to select that option and move on to next control in the form.  They should not have to use the mouse to finish the selection, or use the down-arrow to move down to the one and only selection.

To repro, run the example code app, first example (I'm using Server-side Blazor):
1) Type 'tracy' in search box
2) Notice only one selection is remaining, Tracy Gwinnell
3) Hit Enter key.  Nothing happens (expected behavior: Tracy Gwinnell is selected)
4) Hit Tab key.  Search box is cleared, nothing is selected. (Expected behavior: (Tracy Gwinnell is selected, focus moves to Submit button)

If, when the user hits Enter/Tab, there are still multiple items in the list, perhaps it should just pick the first one?

**Comment by vertonghenb** [comment]
@rgamage Good catch!
Currently you can use Tab > Enter.

However it should be pretty easy to implement.

**Comment by rgamage** [comment]
Tab -> Enter doesn't work.  It either selects an empty result, or selects the previous selection you made.

**Comment by vertonghenb** [comment]
True that didn't work, however PR is ready, let me know what you think.

**Comment by rgamage** [comment]
Thanks for the quick response!  That looks like it might work for Enter, would it be a similar code change for Tab? I would think Tab would be the primary use case.  As a user, if the entire 'form' is just this type-ahead and a submit button, then I would expect pressing Enter would select the item, and click the Submit button (default behavior on form submit buttons).  Basically, it would be nice to be able to optionally pass that Enter key event up the hierarchy, so the Form could act on it, after the typeahead component acts on it.  Kind of like the opposite of event.preventDefault() in a React / JS event handler method.

**Comment by vertonghenb** [comment]
@rgamage I get your use case but it's not something I'd suggest doing since you're basically using the typeahead's select to alter some other state outside of the control itself.
What I'd suggest doing is the following:
1. Type in the name
2. There is only 1 suggestion 
3. Press `Enter`, which will return the focus to the `typeahead` (where it was basically).
4. Press `TAB` which will focus your next element in your case the submit `button`
5. Press Enter to submit the form.

I think this will result in a more defensive user experience.

**Comment by rgamage** [comment]
Ok, understood.  I can tell you from my user's feedback that this 'Enter - Tab - Enter' dance on every part number entry (this is for a part lookup system, used by production workers many times a day), will get very negative feedback.  Users want to type in a part, and go, with a single additional keystroke, not three.  I understand many other devs may disagree, so default may be different, but it would be nice for a general-purpose component like this to have the ability to customize these kinds of behaviors.  At least provide tab and enter hooks that we can use as we please.   I'm not trying to be negative or demanding, understand this is a free open source lib, I'm just advocating to make it even more useful for other devs out there.

Is there a hook to capture when an item is 'selected'?  If so, then I could use your PR that selects upon Enter, then do my own app-specific action when an item is selected.

**Comment by vertonghenb** [comment]
The Parameter `OnValueChanged` could be what you're looking for.

**Comment by rgamage** [comment]
Thanks for the tip on OnValueChanged, and for the "Enter key to Select" code - I will give it a try.  I'll enter a separate issue for the odd tab behavior (Tab key clears your text).
