### ISSUE TITLE
Enhancement: Auto-Select on exact match

### ISSUE THREAD

**Issue by rgamage** [Blazored/Typeahead#80]
If the user has entered an exact match to one of the items (so only one item remains in drop-down), it would be nice for the control to automatically Select that item (same as if the user clicked the item in the drop-down with the mouse).  This way, the input field would be properly populated, and the model SelectedItem would be set OnValueChanged fires, etc. and the control would maintain focus, allowing user to Tab to the next control in the form (or backspace and type something else).

This should probably be an optional feature, as some may not want this behavior.  Just an idea I think would be useful for keyboard-biased users who don't want to use the mouse to select their item, after they've already completely typed it in.

**Comment by vertonghenb** [comment]
I like the idea but this could cause some issues in my option. I've been trying to find an example of antoher autocomplete component that works as you mentioned but I wasn't able to find any.

- https://material-ui.com/components/autocomplete/
- https://mdbootstrap.com/docs/jquery/forms/autocomplete/
- https://www.syncfusion.com/angular-ui-components/angular-autocomplete

I think that using the `Enter` key makes it more explicit 
related to #77

**Comment by chrissainty** [comment]
I agree @vertonghenb. I've not seen this kind of behaviour in other controls of this type and it might catch people off guard it they are typing and all of a sudden a item is selected without a deliberate action.
