### ISSUE TITLE
Control should retain focus when a selection has been made

### ISSUE THREAD

**Issue by chrissainty** [Blazored/Typeahead#81]
When a selection is made the control does not retain focus when it swaps back into the template mode. This only matter when selecting a single value, not when the control is in multi-select mode.

The desired behaviour is when a selection is made the suggestions list closes the new selected template is displayed and the control still has focus. This means that the next tab would move to the next control. Currently two tab presses are needed.

**Comment by vertonghenb** [comment]
Mmm I'm wondering how this could work since the `<input/>`  won't be in the render tree anymore since the template or `mask` is present.

**Comment by chrissainty** [comment]
Yes, this is an issue. I've tried a few different... hacks. I'm not getting anywhere fast to be honest.

**Comment by vertonghenb** [comment]
Another point of view is to go to the next control

**Comment by chrissainty** [comment]
How could we make this go to the next control? Unless anyone has some suggestions on this I'm going to close as a won't fix for now as I'm out of ideas.
