### ISSUE TITLE
The X symbol is giving me grief

### ISSUE THREAD

**Issue by kiwiingenuity** [Blazored/Typeahead#83]
My BlazoredTypaheadInput was working fine before the last update.
I have altered the code now to be only BlazoredTypahead and I have added ShowDropDownOnFocus="true", which gives me similar functionality to what I had before the update.

Now if I click on an item, the dropdown appears and with my mouse I can select a new option.
All good to this point.

However next to the current item there a cross (X). If I click on the cross X (which I note doesn't appear on your screen shots) the dropdown will appear as expected, but I'm unable to select a new option.

Is anyone else experiencing the same?

I'm using Blazor WebAssembly and the target framework is netstandard2.0
The sever app is netcoreapp3.1

**Comment by masudijames** [comment]
When I press X it seems the Model is cleared also. Checking the console I get the following error:

**System.InvalidOperationException: EditForm requires a Model parameter, or an EditContext parameter, but not both.
   at Microsoft.AspNetCore.Components.Forms.EditForm.OnParametersSet()**

Any suggestions

**Comment by kiwiingenuity** [comment]
Further investigation... I have discovered it's the same issue as with the drop down Icon issue I created, namely I get the error message 
Microsoft.JSInterop.JSException: Could not find 'addKeyDownEventListener' in 'window.blazoredTypeahead'
I will check my source code in more detail!
@masudijames I don't believe we are experiencing the same issue?

**Comment by chrissainty** [comment]
@masudijames As the error states, have you specifiec a model parameter on your `EditForm` component?

**Comment by masudijames** [comment]
Is it necessary to use ViewModel like SelectedPerson as in your example or I can directly use 
<EditForm Model="person" OnValidSubmit="HandlValidSubmit">

**Comment by chrissainty** [comment]
@masudijames Sorry I don't know what you mean. I would probably be much more helpful if you shared your code.

**Comment by masudijames** [comment]
```

@page "/StudentCreate"
@using DependencyinjectionDemo1.Services

<h3>StudentCreate</h3>

<EditForm Model="@Student"  OnValidSubmit="@SaveStudent">
    <DataAnnotationsValidator />
      <BlazoredTypeahead SearchMethod="SearchStudent"
                               @bind-Value="@Student.StudentClassId" EnableDropDown="true"
                               placeholder="Search by first name..."
                               ShowDropDownOnFocus="true">
                <SelectedTemplate Context="studentClass">@Student.Name</SelectedTemplate>
                <ResultTemplate Context="studentClass">
                    @Student.Name
                </ResultTemplate>
            </BlazoredTypeahead>       
    <InputText @bind-Value="Student.Name"></InputText>
    <ValidationMessage For="@(() => Student.Name)" />
    <ValidationMessage For="@(() => studentClass.Name)" />
    <button type="submit" class="btn btn-success">Submit</button>
</EditForm>


@code {
    [Inject]
    public IStudent StudentService { get; set; }
    [Inject]
    public IStudentClass StudentClassService { get; set; }


        protected Student Student { get; set; }
    StudentClass studentClass = new StudentClass();
    

    [Parameter]
    public IEnumerable<StudentClass> StudentClasses { get; set; }

    public async Task SaveStudent()
    {
        await StudentService.SaveStudentsAsync(Student);

    }

    private async Task<IEnumerable<StudentClass>> SearchStudent(string searchText)
    {
                StudentClasses = await StudentClassService.GetStudentClassesAsync();
                return await Task.FromResult(StudentClasses.Where(x => x.Name.ToLower().Contains(searchText.ToLower())).ToList());
    }
}

```
**the following is Student.cs**

```
 public class Student
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Please add students name")]
        public string Name { get; set; }
        public int StudentClassId { get; set; }
        public StudentClass StudentClass { get; set; }

    }

```
**the following is StudentClass.cs**
```  

public class StudentClass
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
        public virtual ICollection<Student> Student { get; set; }

    }

```

I really appreciate your help

**Comment by chrissainty** [comment]
Try newing up your Student property

```
protected Student Student { get; set; } = new Student();
```

**Comment by masudijames** [comment]
Did that but now I get another error in  Selected Template. The error treats studentClass as int instead of StudentClass studentClass and now @studentClass.Id gives error
```
<SelectedTemplate Context="studentClass">**@studentClass.Id**</SelectedTemplate>
                <ResultTemplate Context="studentClass">
                    @studentClass.Name
                </ResultTemplate>

```

**Comment by chrissainty** [comment]
As you're binding to an `int` value, you are only being provided that value in the selected template. You will need to add a lookup method to find the student from the ID, something like this.

```html
<SelectedTemplate Context="studentClass">
    @LookupStudent(studentClass)?.Name
</SelectedTemplate>

@code {
    public Student LookupStudent(int? id)
    {
        var student = // code to find student from ID
        return student;
    }
}
```

**Comment by masudijames** [comment]
I have two tables **Student** and **StudentClass**, this EditForm is a form for student table which contains the columns **Id**, **Name** and foreign key **StudentClassId** .
This form has **Student Name** and **dropdown of studentClass (typeahead)**. I think i need to rearrange my code but still it doesnot work

**Comment by chrissainty** [comment]
Have you looked at the samples by any chance? There is an example which is doing exactly what I think you're attempting to do. You can [view it here](https://github.com/Blazored/Typeahead/blob/6b0eaadce54b4b88131e990314e9005edc2af0f7/samples/BlazorServerSide/Pages/Index.razor#L78). It searches a list of people but binds to an `int` value.
