### ISSUE TITLE
EnableDropDown does not show the arrow symbol

### ISSUE THREAD

**Issue by kiwiingenuity** [Blazored/Typeahead#84]
If I set EnableDropDown="true", then down arrow icon which shows on your docs is not there.
There is a blank area to the right that if I click does show the dropdown.

I'm using Blazor WebAssembly and the target framework is netstandard2.0
The sever app is netcoreapp3.1

**Comment by vertonghenb** [comment]
@kiwiingenuity Thanks for reporting this.
However I cannot seem to replicate the issue you're mentioning. The .Client sample in the samples folder seems to be doing fine. It might be a css related issue. 

Is it possible to send us a repository with the code you're having issues with (it can be a smaller proejct if it contains IP)?

**Comment by kiwiingenuity** [comment]
I've downloaded the source code and attempted to replicate this issue and failed to do so.
This leads me to believe I will have to look a bit harder at my code???
I'm experiencing the error. 

Microsoft.JSInterop.JSException: Could not find 'addKeyDownEventListener' in 'window.blazoredTypeahead'.

**Comment by chrissainty** [comment]
@kiwiingenuity Have you checked to make sure both the blazored-typeahead.js file and the blazored-typeahead.css file are being included in your application?

**Comment by kiwiingenuity** [comment]
I checked the .js and .css, looking at the Network tab they both had a status of 200.
I noted it was memory cached, so I thought I would try to clear my cache and try again.
This resolved the issue!  The arrow Icon is now showing.
Thank-you for your help.
