### ISSUE TITLE
TypeInference.CreateBlazoredTypeahead_0 Error on new BlazorServerSide project

### ISSUE THREAD

**Issue by cyberyaga** [Blazored/Typeahead#85]
I'm running on Linux {Pop_Os 19.10}
VS Code 1.40.1
Dotnet 3.0.1

I wanted to make sure that my code was not the issue. So I created a brand new project on dotnet core 3.0.1 blazorserver template.

I compiled and run the empty project fine.

I do the install steps here: https://chrissainty.com/getting-started-with-blazored-typeahead/

I take the sample code on the page that's under "Usage Example" and paste it to the Index.razor.

And immediately I get this compile error:
`/home/cyberyaga/ProjectsTest/BlazorServerSide/obj/Debug/netcoreapp3.0/Razor/Pages/Index.razor.g.cs(89,65): error CS0411: The type arguments for method 'TypeInference.CreateBlazoredTypeahead_0<TItem, TValue>(RenderTreeBuilder, int, int, Func<string, Task<IEnumerable<TItem>>>, int, TValue, int, EventCallback<TValue>, int, Expression<Func<TValue>>, int, RenderFragment<TValue>, int, RenderFragment<TItem>)' cannot be inferred from the usage. Try specifying the type arguments explicitly. [/home/cyberyaga/ProjectsTest/BlazorServerSide/BlazorServerSide.csproj]`

Let me know if you need additional details. I would really love to use this component.

Thanks

**Comment by vertonghenb** [comment]
Thanks for bringing this up, is there a repository with the source code?

**Comment by cyberyaga** [comment]
Not really... I just the 3-4 steps in the documentation... and the just copy pasted the code in the "Usage Example" into the Index.razor, and hit F5... 

I was just making sure that my code wasn't the issue, since it doesn't work on my main project neither. And my main project is not public.

I might bring down this project and try to debug it and see if I come across why I'm getting this error when running.

Thanks for the quick response.

**Comment by chucker** [comment]
Could you post both the `Index.razor` and the generated `obj/Debug/netcoreapp3.0/Razor/Pages/Index.razor.g.cs`?

Inside that project, what is the output of `dotnet --info`?

**Comment by cyberyaga** [comment]
**Index.razor** I added the .txt extension to get it to upload.
[Index.razor.txt](https://github.com/Blazored/Typeahead/files/3898509/Index.razor.txt)

**Index.razor.g.cs**
[Index.razor.g.cs.txt](https://github.com/Blazored/Typeahead/files/3898517/Index.razor.g.cs.txt)

**Comment by vertonghenb** [comment]
Mmm, haven't tested it yet but could it be because the `Film` class is an implicit `private class` instead of `public`? try adding the `public` keyword infront of the `class Film`.

**Comment by cyberyaga** [comment]
Just tried making the Films class public... Still the same issue.

Looking at the Index.razor.g.cs file, it seems like it has an issue generating the BlazoredTypeahead component. If I leave all the code intact and just remove the BlazoredTypeahead component from the Index.razor file, it compiles and runs fine.

The issue happens when the BlazoredTypeahead component markup is in the file.
[BlazorServerSide.zip](https://github.com/Blazored/Typeahead/files/3899183/BlazorServerSide.zip)

I managed to zip the entire project here... Maybe you can figure out what the root cause is.

Thanks

**Comment by chrissainty** [comment]
Hi @cyberyaga,

I downloaded you code and I've spotted the issue, unfortunately Blazor's error's haven't helped us much here. The problem is actually in how you've defined your `SearchFilms` method.

```csharp
private async Task<List<Film>> SearchFilms(string searchText)
{
    return await Task.FromResult(Films.Where(x => x.Title.ToLower().Contains(searchText.ToLower())).ToList());
}
```

We changed the signature of the search method in the last major release and we now require a return type of `IEnumerable<T>` not `List<T>`. Once that is changed everything works fine.

**Comment by cyberyaga** [comment]
Worked like a charm... Thanks for taking a look at this.

**Comment by cyberyaga** [comment]
BTW... Under "Forms Integration" in your documentation page, you have a tag mismatch:
<BlazoredTypeahead></BlazoredTypeaheadInput>

**Comment by chrissainty** [comment]
Fixed
