### ISSUE TITLE
Cannot bind (convert) to Guid

### ISSUE THREAD

**Issue by NatanBagrov** [Blazored/Typeahead#86]
When trying to bind to `Guid`, there is the following compilation error:

`  Index.razor.g.cs(329, 65): [CS0411] The type arguments for method 'TypeInference.CreateBlazoredTypeahead_4<TItem, TValue>(RenderTreeBuilder, int, int, Func<string, Task<IEnumerable<TItem>>>, int, Func<TItem, TValue>, int, object, int, TValue, int, EventCallback<TValue>, int, Expression<Func<TValue>>, int, RenderFragment<TValue>, int, RenderFragment<TItem>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.`

Repro: given the code from the examples - change `Person.Id` from `int` to `Guid` (and the conversion methods, too).

**Comment by NatanBagrov** [comment]
BTW, I tried to figure out how to resolve this issue, but I guess that it's a Blazor thingy...

**Comment by chrissainty** [comment]
Hi @NatanBagrov, I've just tried this and everything is working as expected. I suspect you're not using a nullable `Guid` perhaps?

**Comment by chrissainty** [comment]
@NatanBagrov As I've not heard anything I'm going to assume you've resolved your issue. I'm going to close this issue but please feel free to reopen if you're still having a problem.

**Comment by NatanBagrov** [comment]
@chrissainty You were correct. Sorry for the delay.
