### ISSUE TITLE
doesnt work in "netstandard2.1"

### ISSUE THREAD

**Issue by RichardBr** [Blazored/Typeahead#89]
This code no longer works for me as I have upgraded my blazor-client project to "netstandard2.1". Can you please update this code.

**Comment by chrissainty** [comment]
Yep, I'm doing my best but you know, the full-time job, 10 packages to maintain, family, etc...

**Comment by RichardBr** [comment]
...it was just a polite request. I am sorry it did not come across that way :)

**Comment by chrissainty** [comment]
No worries, why not have a go at updating the package and raising a PR? Open source works so much better when everyone lends a hand :)

**Comment by chrissainty** [comment]
@RichardBr Had a sec to think about this. When you say it doesn't work, what do you mean?

**Comment by chucker** [comment]
Hmm, I can't confirm this. I changed the BlazorClientSide project to use .NET Standard 2.1 and to use Typeahead from NuGet rather than from the solution, and it still worked.

**Comment by chrissainty** [comment]
Thanks @chucker. Did you have any issues with the CSS or JS not being loaded? I've spoken to a few people today who've had to reference them in the same way as Blazor Server (which I know has been coming for a while).

**Comment by RichardBr** [comment]
![typeahead error](https://user-images.githubusercontent.com/5938313/70173770-7a0bfe80-16cb-11ea-8419-d601c1f79e68.png)

**Comment by chrissainty** [comment]
@RichardBr thanks for the info. Could you try adding the following to you `index.html`

In the head tag add the following CSS.
```
<link href="_content/Blazored.Typeahead/blazored-typeahead.css" rel="stylesheet" />
```
Then add the JS script at the bottom of the page using the following script tag.
```
<script src="_content/Blazored.Typeahead/blazored-typeahead.js"></script>
```

**Comment by RichardBr** [comment]
That fixed the problem :)

**Comment by chucker** [comment]
Ah, yes. OP is probably running into https://github.com/aspnet/AspNetCore/issues/17535, which probably happened after switching frameworks because:

>Workaround:
>
>Close and reopen the solution, rerun the app

**Comment by chrissainty** [comment]
@chucker I think the issue is that static assets don't seem to be being referenced automatically anymore

**Comment by chrissainty** [comment]
@RichardBr Glad we got it sorted.

**Comment by RichardBr** [comment]
> @RichardBr Glad we got it sorted.

Thank you for your speedy assistance.

**Comment by MarkStega** [comment]
@RichardBR I went ahead and created a PR for DNC 3.1
