### ISSUE TITLE
Add a default value parameter for search text

### ISSUE THREAD

**Issue by julienGrd** [Blazored/Typeahead#96]
Hello chris, and thanks for your work on this project.

I would like to have an option to initialized the search text with a default value, and ideally directly launch the research at the startup (with this default value).

Do you think its possible.

I can suggest a PR if needed.

thank you !

Julien

**Comment by chrissainty** [comment]
Currently, you can initialise the Typeahead with an initial value, is that what you mean?

**Comment by julienGrd** [comment]
Yes but it's an initial value of type TItem no ? what i want is to initialise the text written by the user (without selected a value, for example just initialise the input with a "r" and launch the search method directly).

But if its so big deal don't worry, i have to change the behavior of your component directly so i will use them as a branch and make my updates only for me.

**Comment by chrissainty** [comment]
I never said it was a big deal, I was just understanding what you were asking for. 

I'm not sure if there would be a wide enough use case for this function to warrant putting it in. But if you're forking the code anyway then you can make whatever changes you wish.

**Comment by vertonghenb** [comment]
Personally I would advice against it because you're mutating the internal state of the component which wasn't our intend. Since it's being forked, I'm closing this one for now until we get more demand for this.
