### ISSUE TITLE
add an option to stopPropagation

### ISSUE THREAD

**Issue by julienGrd** [Blazored/Typeahead#98]
Hi Chris, i have a request again

I have a conflict with the OnKeyUp event which is also launch on my side on a parent component (a bootstrap modal actually). I don't know why, but it make the input crazy (the text entered disappear).

I not suceed to reproduce in a simple example, but add the directive @onkeyup:stopPropagation on your input solve all my problems.

It is possible to add a parameter to add this directive ? 

I can suggest a PR

thanks !

Julien

**Comment by chrissainty** [comment]
Hi Julien,

That makes sense, more than happy to take a PR to sort this. I assume it's the `@onkeyup` event on the `input` controls?

**Comment by julienGrd** [comment]
yes it's what i was thinking. But maybe let user drive it with a parameter of your component ?

somethink like that, with StopPropagation a parameter initialize to false
````
<input @ref="_searchInput"
            @bind-value="SearchText"
            @bind-value:event="oninput"
            @onkeyup="HandleKeyup"
            @onkeyup:stopPropagation="@StopPropagation" <!-- New Change -->
            @onblur="ResetControl"
            @onfocus="HandleInputFocus"
            @attributes="AdditionalAttributes"
            autocomplete="off"
            type="text"
            class="blazored-typeahead__input @(IsShowingMask ? "blazored-typeahead__input-hidden" : null)" />
````
what do you think ?

**Comment by chrissainty** [comment]
I think that's a good idea, that way if consumers do want to have the event propagate up then they can have that control.

**Comment by julienGrd** [comment]
ok i will make the PR on this way
